### ISSUE TITLE
'Debug' command as an alternative to execute/print/inspect

### ISSUE THREAD

**Issue by jgfoster** [jgfoster/Jade.bak#10]

**Comment by brunobuzzi** [comment]
This can be solved with quick and dirty code (self is aGciSession):
| oopType |
oopType := self executeString: 'self halt. OrderedCollection new'.
JadeDebugger 
openOn: (GsProcess session: self oopType: oopType) 
message: 'Debug It'
terminateOnClose: true.

Executing this in Dolphin i get a Gs Debugger. The ugly thing is the halt at the first step in the Stack.

**Comment by brunobuzzi** [comment]
The following code is a little better (but still not the best way to open a debugger).
In this case 'OrderedCollection new + #()' will be debugged.
| oopType debuger |
oopType := [self executeString: 'Breakpoint signal.', String lineDelimiter,'OrderedCollection new + #().'] on: GsError do: [:ex |
debuger := JadeDebugger 
			openForDebug: ex gsProcess 
			message: 'Debug It'
			terminateOnClose: true.
].
Where "openForDebug:message:terminateOnClose:" is a new method:
openForDebug: gsProcess message: aString terminateOnClose: aBoolean
	^(self showOnSession: gsProcess gciSession)
		initializeProcess: gsProcess message: aString terminateOnClose: aBoolean;
		stepOut; stepOut; "close the steps of the -Breakpoint signal- code"
		answer.
