### ISSUE TITLE
Undefined symbols in a workspace

### ISSUE THREAD

**Issue by obi068** [jgfoster/Jade.bak#101]
You get a lot of dialogs if you execute a workspace with undefineds

**Comment by jgfoster** [comment]
I'm unable to reproduce this problem. What version of Jade are you using?

**Comment by obi068** [comment]
This happens with all versions since a year i think. My current version is 2.1.2.
e.g.
Put "asdfg" in the workspace
then inspect (CTRL+Q) 
=> I have to close 4 dialogs

![image](https://cloud.githubusercontent.com/assets/1876280/26616984/d538bb62-45d2-11e7-9c5c-47dbc9d2057b.png)

![image](https://cloud.githubusercontent.com/assets/1876280/26616991/ee5ee4cc-45d2-11e7-9901-950728521e23.png)

**Comment by obi068** [comment]
Fixed with 2.1.5
