### ISSUE TITLE
Error when inspecting a Float

### ISSUE THREAD

**Issue by baderth** [jgfoster/Jade.bak#105]
Reproduce: 
"60 asFloat"

Expected behaviour: Getting the Float displayed.
Current behaviour: Error, see attached.

![image](https://user-images.githubusercontent.com/1823917/27949757-2b896c84-62ff-11e7-892c-e0194f279fd2.png)

**Comment by jgfoster** [comment]
This seems to have been a deeper problem with all "special" objects (Integer, Character, Boolean, etc). It may have been introduced with the new inspector.
