### ISSUE TITLE
Latest Versions (2.1.10) System Browser is broken

### ISSUE THREAD

**Issue by baderth** [jgfoster/Jade.bak#108]
Installed all supporting libs as it requires a new version, but every time I click on a method I get exceptions: 

![image](https://user-images.githubusercontent.com/1823917/28106635-e1c7d4ca-66e4-11e7-81f4-889602c03054.png)

**Comment by jgfoster** [comment]
Sorry about that. I'm trying to get Jade ready for GS 3.4 and it has some new features. This should use the proper code for pre-3.4 servers.
