### ISSUE TITLE
2.1.15 - Can not load any packages from Monticello Browser

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade.bak#114]
I just noticed today, that I can not load packages any more into the databasefrom the Monticello Browser.

Assuming I want to load a package "MSKRESTSupport" and a version "MSK.6009" is shown. I select the package and the version and then "Load Version" and I get an error:

"a UserDefinedError occurred (error 2318), reason:halt,  file not found, errno=2,ENOENT, The file or directory specified cannot be found : /home/mf/development/transfer64/MSKRESTSupport.package"

The server directory is "/home/mf/development/transfer64" which is a correct path

JadeServer64bit33>>mcVersionLoad: aString fromFile: anMCFileBasedRepository autoMigrate: aBoolean

	| version package workingCopy mcPlatformSupport autoMigrate |
	mcPlatformSupport := self objectInBaseNamed: #'MCPlatformSupport'.
	autoMigrate := mcPlatformSupport autoMigrate.
	mcPlatformSupport autoMigrate: aBoolean.
	version := anMCFileBasedRepository loadVersionFromFileNamed: aString.
	version load.
	package := version package.
	workingCopy := self mcWorkingCopyClass forPackage: package.
	workingCopy repositoryGroup addRepository: anMCFileBasedRepository.
	mcPlatformSupport autoMigrate: autoMigrate.

is called with aString = 'MSKRESTSupport.package' and anMFCFileBaseDepository is pointing toward a server directory

aMCServerDirectoryRepository(gemstone:/home/mf/development/transfer64)

**Comment by jgfoster** [comment]
First, there is a problem with MCPlatformSupport class>>readStreamForFileNamed:onClient:do: in which it uses GsFile class>>lastErrorString to report an error. This is the correct method for a client error, but if there is a server error then GsFile class>>serverErrorString should be used. That is a problem with the base extent0.seaside.dbf and I'm not sure if/how it will be fixed.

Second, we are passing in a filename that isn't recognized. I should be able to address that problem.

**Comment by feldti** [comment]
Hello James, it becomes a rea, reall problem here, if I can not load any package from the monticello repository browser ....
