### ISSUE TITLE
BitBucket support?

### ISSUE THREAD

**Issue by HeSe** [jgfoster/Jade.bak#115]
Hi James!

I use BitBucket server to maintain a new pahro project of mine.
Is there any way to access or define a BitBucket repository from Jade?

Thanks
Sebastian

**Comment by HeSe** [comment]
I did some research...
There seems to be a Bitbucket.org implementation available in Pharo, but is is different to the Jira based local bitbucket server api. 
I will try out if I can make this work from within Pharo and if so, I hope to get that added to Metacello.

So, you can close this issue. There is no suport for this. It just would be great to have it.

**Comment by jgfoster** [comment]
Once it is in Metacello/Monticello on Pharo, and ported to Gemstone, then we should be able to add it to Jade.
