### ISSUE TITLE
Slow method selection performance

### ISSUE THREAD

**Issue by jgfoster** [jgfoster/Jade.bak#117]
MK reports that with a Jade circa 2012 method selection takes ~45ms while with a current version (2.1.15) it takes 2995ms. This is on a database with 5,400 classes and 88,000 instance methods. When the same action is done with a base database we see no delay. I suspect that the problem is with searching for implementors and superclass implementations.

**Comment by PeterMoe** [comment]
Hello,
i have tested the method selection in 1.077 and the current versions, the server perform Time (first time in status bar after selection change) delay is about 1000 ms = 1 second.
now i read some of the code for the Method selection. (i hope its the right one)
and i found at Class GciSession the instance Method:

`withExplanation:doA:`

In line 15 the code:
`(Delay forSeconds: 1) wait.`

@jgfoster why do you wait for 1 second ?

**Comment by jgfoster** [comment]
@PeterMoe, Thank you for looking at this slow performance issue. As to the delay for one second, that deals only with the time before showing the wait dialog that has the Break options. The real work is done in the first forked process (that calls handlingClientForwarderSendDo:). When we have a short call to GemStone (less than one second), then we simply display the GemStone cursor. Once the delay exceeds a second then we fade in the WaitOnGemStoneDialog and continue waiting for the GemStone call to finish. So the delay is to limit the wait dialog to longer calls and not show it on shorter calls. Note that after the one-second delay, the only thing that happens is that shouldRunEventLoop is set to false. When the underlying call to GemStone is done it will set the haveResult flag and the method will return when that flag is set.

To see the difference, try the following in a workspace:
     (Delay forMilliseconds: 250) wait.
     (Delay forMilliseconds: 2500) wait.
You can see that in one case the dialog shows and in the other it does not.

I'll have some other notes on the delay shortly.

**Comment by PeterMoe** [comment]
Thanks for the explanation.

**Comment by jgfoster** [comment]
@PeterMoe, Are you actually editing and running Jade in Dolphin or are you just looking at source code? If you are able to edit code and try changes then take a look at JadeServer>>#_describeMethod: and search for "117" (I have a reference to this issue). Comment out the next seven lines (be sure to leave in the 'writeStream lf'. If this significantly improves the performance, then we've identified the problem. If you aren't in a good position to edit and run, but are willing to try a debug build then let me know and I'll make something up that can help us diagnose the slow performance.

**Comment by PeterMoe** [comment]
@jgfoster I am sitting at home, study the jade source in Dolphin but i can't connect to Gemstone because it's in the office. I have made a portable Dolphin USB-Stick(no admin right on my office laptop) so i can edit and run the code at work on monday.

**Comment by PeterMoe** [comment]
@jgfoster you a right, when i comment the code in #_describeMethod: i have no delay when i uncomment the code, the delay is back.
Did i read it right in the sourcecode, you do this for register the uncommited method for JadeAutocompletation ?

**Comment by jgfoster** [comment]
@PeterMoe, Thanks for confirming the problem. The code is related to looking for unimplemented messages and if there are a lot of methods then this search evidently takes some time. I'll add a preference to disable this (unless I can find a way to make it fast!).

**Comment by jgfoster** [comment]
With 2.1.25 (09e9b3273431b4a6895096eea7ef08f11a3d9c3d) there is a preference (available from the Transcript window) to uncheck showing unimplemented messages. As a separate matter I'll look at saving preferences so you don't have to adjust it with each login. Please reopen this if you still have an issue.
