### ISSUE TITLE
Debug takes 2 clicks to work

### ISSUE THREAD

**Issue by nrgiii** [jgfoster/Jade.bak#122]
If I select some code in a workspace and right click "Debug", the first attempt does nothing. Repeating the same executes the code in the debugger.

**Comment by jgfoster** [comment]
Server bug in  3.5 (http://kermit.gemtalksystems.com/bug?bug=47437) and earlier.

**Comment by jgfoster** [comment]
If Jade is going to invoke _compileInContext:...setBreakAtStepPoint: 1 ...
then it needs to use a flags arg of  0x21 using one of the
GciExecute variants that has an
  int flags
argument, i.e. with the following bits set in flags:
 GCI_PERFORM_FLAG_ENABLE_DEBUG=1,
 GCI_PERFORM_FLAG_INTERPRETED=20
for the execution.

The topaz equivalent of that GciExecute would be to use INTERP and not RUN to simulate the execution .
