### ISSUE TITLE
Feature request: keyboard shortcuts

### ISSUE THREAD

**Issue by nrgiii** [jgfoster/Jade.bak#123]
It would be nice if Jade supported keyboard shortcuts like other ST IDEs do.  Some of the ones I remember:

<ctrl>-g  insert  ':='
<ctrl>-t insert 'ifTrue:[]'
<ctrl-f> insert 'ifFalse:[]'
highlight some text,, then <ESC>-( - surround highlighted text in parenthesis
highlight some text,, then <ESC>- [ -  surround highlighted text in square brackets

I'm sure there are many others I'm missing but these would be a nice start.

**Comment by brunobuzzi** [comment]
I'm working on shortcuts but if you:
1) Enable autocompletion
2) Select Boolean, False and True in the System Browser 
(autocompletion does no call the server to display methods but rather store classes and methods as the user do clicks on the System Browser) (to teach the autocompletion available methods)
3) type "if"it should pop up ifTrue> ;'
![image](https://user-images.githubusercontent.com/4719282/35476872-9ee91f8e-0396-11e8-90b7-84fb82591d0d.png)
I will appreciate any autocompletion feedback or bug reports

**Comment by nrgiii** [comment]
Thanks!

**Comment by brunobuzzi** [comment]
Still working on:
highlight some text,, then -( - surround highlighted text in parenthesis
highlight some text,, then - [ - surround highlighted text in square brackets

**Comment by jgfoster** [comment]
Norm, I'm going to reopen this to track that I need to merge Bruno's contribution and do an actual build/release.

**Comment by jgfoster** [comment]
Basic functionality includes -g, -t, -f, -b, -v. More can be added easily.
