### ISSUE TITLE
Jade debugging 2.4.x broken

### ISSUE THREAD

**Issue by nrgiii** [jgfoster/Jade.bak#141]
In class JadeProcessBrowser in method addProcess: aProcess to: aStream withStatus: aString scheduler: aScheduler,

The message #stackId is sent to aGsProcess.  The stackId method does not exist in GS/64 2.4.x and raises this error:

No method was found for the selector #'stackId' when sent to GsProcess(oop=16749313, status=ready, priority=10,

**Comment by jgfoster** [comment]
The problem with opening the Process List in 2.4.x has been fixed.
