### ISSUE TITLE
Jade broken with latest 3.5

### ISSUE THREAD

**Issue by nrgiii** [jgfoster/Jade.bak#143]
Login fails with this in netldi log:

--- 05/24/18 10:26:06.740 PDT accept failed,  invalid response (old version client?) Invalid client connectKind

The RPC  protocol has  changed recently so Jade needs to be packed with a more recent version of the GCI dll.

**Comment by jgfoster** [comment]
With Jade 2.1.22 I'm able to log in to GS/64 3.5.0 (44163).
