### ISSUE TITLE
Jade 2.1.24-1-g5615471: Wrong display of german umlauts 

### ISSUE THREAD

**Issue by PeterMoe** [jgfoster/Jade.bak#149]
Hello,
i am using Gemstone 2.4.6 and Jade 2.1.24-1-g5615471
Umlauts ÖÄÜ ß are not correct displayed:

![umlaute](https://user-images.githubusercontent.com/40350726/41654200-345cbb1e-7478-11e8-9aa1-fa0b9d5dc6e9.JPG)

in Jade version 1.077 the umlauts are correct displayed:

![umlaute_ok](https://user-images.githubusercontent.com/40350726/41654334-a583b36a-7478-11e8-93a1-4d3eb9e4cae4.JPG)

**Comment by PeterMoe** [comment]
Info: Jade 2.1.23 had no problems with umlauts:
![umlaute2 1 23](https://user-images.githubusercontent.com/40350726/41657775-f78b1742-7483-11e8-8822-fa984bd2d251.JPG)

**Comment by jgfoster** [comment]
Dolphin 7.1 has changes in Unicode/UTF8 that is probably related. I will investigate but it might be more than a day or two, so the earlier version might be better given the small fix in the recent version.

**Comment by jgfoster** [comment]
I believe this is fixed in v2.2.0.

**Comment by jgfoster** [comment]
@brunobuzzi, Since you are looking at things and have more multilingual experience than I do, I'd welcome any comments you have on this rewrite. Are you able to enter and view Spanish characters as you expect (against GS/S 64 Bit 3.3.0 or later) and do things work as before on earlier versions? Thanks!

**Comment by brunobuzzi** [comment]
@jgfoster trying to compile the following on Jade (forked today) and GS 3.4.1:
test
	^'áóúñé'
I got the following walkback:
UserDefinedError (AbstractException) >> _signalWith: @6 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
SqNumberParser (Object) >> error: @6 line 7
SqNumberParser (NumberParser) >> expected: @14 line 8
SqNumberParser >> readNamedFloatOrFail @20 line 24
SqNumberParser >> nextNumber @9 line 13
Number class >> readFrom: @3 line 8
Unicode16 (CharacterCollection) >> asNumber @3 line 5
JadeServer64bit34 (JadeServer) >> sbClassFrom: @9 line 5
JadeServer64bit34 (JadeServer) >> sbSaveMethod: @3 line 5
JadeServer64bit34 (JadeServer) >> _systemBrowserCommand @122 line 40
[] in JadeServer >> systemBrowserA: @24 line 10
Time class >> secondsElapsedTime: @6 line 11
Time class >> millisecondsElapsedTime: @2 line 6
JadeServer64bit34 (JadeServer) >> _millisecondsElapsedTime: @2 line 3
JadeServer64bit34 (JadeServer) >> systemBrowserA: @3 line 4
JadeServer64bit34 (JadeServer) >> systemBrowser: @3 line 3
[] in JadeServer64bit >> systemBrowser: @7 line 4
ExecBlock0 (ExecBlock) >> on:do: @3 line 44
JadeServer64bit34 (JadeServer64bit) >> systemBrowser: @3 line 5
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by brunobuzzi** [comment]
Sorry James,
The previous error was caused because no class was selected. 
With a class selected no compile error --> you can ignore the above.

**Comment by jgfoster** [comment]
Actually, if not having a class selected can cause an error (walkback), then it would be nice to catch it earlier and give a more friendly explanation.
