### ISSUE TITLE
Jade 1.0.81 - Menu Edit does not work in the browser 

### ISSUE THREAD

**Issue by MFeldtmann** [jgfoster/Jade.bak#15]
Was already defect in 1.0.80

**Comment by MFeldtmann** [comment]
When pressinf right mouse one gets a dialog "out of bounds"

**Comment by MFeldtmann** [comment]
The dialog pops only up, when nothing is selected in the text pane f the browser ...

**Comment by jgfoster** [comment]
A further side-effect of the new open browser tab on a selected class feature. If nothing was selected then we got a range error when trying to determine if the selected text could be a class. Now we check to see if the selection is empty. Fixed by d88fc2318ac043f756f777f2582fa681c68a3fb0.
