### ISSUE TITLE
FIx JadeAutoTextPresenter3>>getCurrentWord for UTF-8

### ISSUE THREAD

**Issue by jgfoster** [jgfoster/Jade.bak#152]
As part of the UTF-8 support work (#149), I needed to bypass JadeAutoTextPresenter3>>getCurrentWord. This issue will track restoring that feature.

**Comment by brunobuzzi** [comment]
Checking this issue. It's been reimplemented right now with Scintilla api (tokenStartAt:, tokenEndAt:).
