### ISSUE TITLE
Create new client files as UTF-8 but preserve ability to read existing ANSI files

### ISSUE THREAD

**Issue by PeterMoe** [jgfoster/Jade.bak#153]
hello,
i am using Branch Jade Unicode and last Dolphin master. When using menu "file out Method", it saves the file in ANSI, no support for Umlauts and german characters.

**Comment by PeterMoe** [comment]
the pull request looks a little bit ugly so i closed it, only want to change JadeSystemBrowserPresenter>>#fileOutMethodOnPath: line 13 type: #'ansi' to type: #'utf8'.
This fixes the issues

**Comment by PeterMoe** [comment]
When using file Out Method UTF8 we must adapt the
JadeFileIn>>#fileInPath:session: line 4 type: #'ansi' to type: #'utf8'

**Comment by jgfoster** [comment]
With #151 we changed all client file operations to use ANSI so that we were backwards compatible. It will take more than simply modifying one line in one method to deal with switching to UTF-8 files while maintaining backwards compatibility.

**Comment by jgfoster** [comment]
This should be supported in v.2.2.0.
