### ISSUE TITLE
Can't open Class browser

### ISSUE THREAD

**Issue by obi068** [jgfoster/Jade.bak#162]
Version 2.2.2

![image](https://user-images.githubusercontent.com/1876280/42861100-e5a642f4-8a59-11e8-912f-70840268df83.png)

**Comment by jgfoster** [comment]
@obi068, I'm not able to easily reproduce this in my environment (with a new 3.5 repository). Is there an error log available (if so, please limit the size to the most recent error)? What version of GemStone do you have? Is Seaside included?

**Comment by obi068** [comment]
GemStone 3.4.0.
Seaside included.
Works with V2.2.1.
************************** Dolphin Virtual Machine Dump Report ***************************
19:33:14, 18.07.2018: Not found: Packages
*----> VM Context <----*
Process: {1B0A0210:size 806 words, suspended frame 1B0A0D9D, priority 5, callbacks 2
last failure 2:nil, FP control 80007, thread 00000000}
Active Method: SessionManager>>logError:
IP: 02486DD9 (9)
SP: 1B0A0F88
BP: 1B0A0F5C (836)
ActiveFrame: {1B0A0F60: cf 1B0A0F41, sp 1B0A0F78, bp 1B0A0F5C, ip 5, JadeSessionManager(SessionManager)>>logError:}
	receiver: a JadeSessionManager
	arg[0]: a NotFoundError
New Method: VMLibrary>>dump:path:stackDepth:walkbackDepth:
Message Selector: dump:path:stackDepth:walkbackDepth:

*----> Stack Back Trace <----*
{1B0A0F60: cf 1B0A0F41, sp 1B0A0F78, bp 1B0A0F5C, ip 5, JadeSessionManager(SessionManager)>>logError:}
	receiver: a JadeSessionManager
	arg[0]: a NotFoundError

{1B0A0F40: cf 1B0A0F21, sp 1B0A0F54, bp 1B0A0F3C, ip 3, JadeSessionManager(SessionManager)>>unhandledException:}
	receiver: a JadeSessionManager
	arg[0]: a NotFoundError

{1B0A0F20: cf 1B0A0F01, sp 1B0A0F34, bp 1B0A0F1C, ip 3, JadeSessionManager(SessionManager)>>onUnhandledError:}
	receiver: a JadeSessionManager
	arg[0]: a NotFoundError

{1B0A0F00: cf 1B0A0EE5, sp 1B0A0F14, bp 1B0A0F00, ip 5, NotFoundError(Error)>>defaultAction}
	receiver: a NotFoundError

{1B0A0EE4: cf 1B0A0EB1, sp 1B0A0EF8, bp 1B0A0ECC, ip 55, NotFoundError(Exception)>>_propagateFrom:}
	receiver: a NotFoundError
	arg[0]: a ExceptionHandler
	stack temp[0]: nil
	stack temp[1]: a ExceptionHandler
	stack temp[2]: nil
	stack temp[3]: a Process('Main' base 1B0A0000* in SessionManager>>logError: sp=00000000 ip=4 list=02760010)
	stack temp[4]: nil

{1B0A0EB0: cf 1B0A0E91, sp 1B0A0EC4, bp 1B0A0EAC, ip 6, NotFoundError(Exception)>>_propagate}
	receiver: a NotFoundError
	stack temp[0]: nil

{1B0A0E90: cf 1B0A0E75, sp 1B0A0EA4, bp 1B0A0E90, ip 13, NotFoundError(Exception)>>signal}
	receiver: a NotFoundError

{1B0A0E74: cf 1B0A0E51, sp 1B0A0E88, bp 1B0A0E6C, ip 8, NotFoundError(Exception)>>signal:with:}
	receiver: a NotFoundError
	arg[0]: nil
	arg[1]: a CardLabel

{1B0A0E50: cf 1B0A0E31, sp 1B0A0E64, bp 1B0A0E4C, ip 5, NotFoundError(Exception)>>signalWith:}
	receiver: a NotFoundError
	arg[0]: a CardLabel

{1B0A0E30: cf 1B0A0E11, sp 1B0A0E44, bp 1B0A0E2C, ip 8, TabViewXP(Object)>>errorNotFound:}
	receiver: a TabViewXP
	arg[0]: a CardLabel

{1B0A0E10: cf 1B0A0DF1, sp 1B0A0E24, bp 1B0A0E0C, ip 12, [] in TabViewXP(ListControlView)>>selection:}
	receiver: a TabViewXP

{1B0A0DF0: cf 1B0A0DC9, sp 1B0A0E04, bp 1B0A0DE4, ip 9, TabViewXP(ListControlView)>>selection:ifAbsent:}
	receiver: a TabViewXP
	arg[0]: a CardLabel
	arg[1]: [] @ 10 in ListControlView>>selection:
	stack temp[0]: nil

{1B0A0DC8: cf 1B0A0DA9, sp 1B0A0DDC, bp 1B0A0DC4, ip 14, TabViewXP(ListControlView)>>selection:}
	receiver: a TabViewXP
	arg[0]: a CardLabel

{1B0A0DA8: cf 1B0A0D8D, sp 1B0A0DBC, bp 1B0A0DA8, ip 6, SlidingCardTray(CardContainer)>>onCurrentCardChanged}
	receiver: a SlidingCardTray

{1B0A0D8C: cf 1B0A0D69, sp 1B0A0DA0, bp 1B0A0D84, ip 13, EventMessageSend>>forwardTo:withArguments:}
	receiver: a EventMessageSend
	arg[0]: a SlidingCardTray
	arg[1]: a Array

{1B0A0D68: cf 1B0A0D4D, sp 1B0A0D7C, bp 1B0A0D68, ip 5, EventMessageSend>>value}
	receiver: a EventMessageSend

{1B0A0D4C: cf 1B0A0D25, sp 1B0A0D60, bp 1B0A0D48, ip 11, [] in MessageSequenceAbstract>>value}
	receiver: nil
	arg[0]: a EventMessageSend

{1B0A0D24: cf 1B0A0CF5, sp 1B0A0D40, bp 1B0A0D10, ip 30, EventMessageSequence>>messagesDo:}
	receiver: a EventMessageSequence
	arg[0]: [] @ 9 in MessageSequenceAbstract>>value
	stack temp[0]: a DeadObject
	stack temp[1]: 1
	stack temp[2]: a SlidingCardTray
	stack temp[3]: a EventMessageSend

{1B0A0CF4: cf 1B0A0CD9, sp 1B0A0D08, bp 1B0A0CF4, ip 15, EventMessageSequence(MessageSequenceAbstract)>>value}
	receiver: a EventMessageSequence
	env temp[0]: nil

{1B0A0CD8: cf 1B0A0CB9, sp 1B0A0CEC, bp 1B0A0CD4, ip 8, EventsCollection>>triggerEvent:}
	receiver: a EventsCollection
	arg[0]: currentCardChanged

{1B0A0CB8: cf 1B0A0C99, sp 1B0A0CCC, bp 1B0A0CB4, ip 4, CardLayout(Object)>>trigger:}
	receiver: a CardLayout
	arg[0]: currentCardChanged

{1B0A0C98: cf 1B0A0C79, sp 1B0A0CAC, bp 1B0A0C94, ip 34, CardLayout>>showCard:}
	receiver: a CardLayout
	arg[0]: a ListView

{1B0A0C78: cf 1B0A0C59, sp 1B0A0C8C, bp 1B0A0C74, ip 8, SlidingCardTray(AbstractCardContainer)>>ensureSubViewVisible:}
	receiver: a SlidingCardTray
	arg[0]: a ListView

{1B0A0C58: cf 1B0A0C3D, sp 1B0A0C6C, bp 1B0A0C58, ip 4, ListView(View)>>ensureVisible}
	receiver: a ListView

{1B0A0C3C: cf 1B0A0C21, sp 1B0A0C50, bp 1B0A0C3C, ip 3, ListPresenter(Presenter)>>ensureVisible}
	receiver: a ListPresenter

{1B0A0C20: cf 1B0A0BF1, sp 1B0A0C34, bp 1B0A0C0C, ip 4, JadeAutoSystemBrowserPresenter(JadeSystemBrowserPresenter)>>updatePackageList}
	receiver: a JadeAutoSystemBrowserPresenter
	stack temp[0]: nil
	stack temp[1]: nil
	stack temp[2]: nil
	stack temp[3]: nil
	stack temp[4]: nil

{1B0A0BF0: cf 1B0A0BCD, sp 1B0A0C04, bp 1B0A0BEC, ip 16, JadeAutoSystemBrowserPresenter(JadeSystemBrowserPresenter)>>updatePackageDictionaryList}
	receiver: a JadeAutoSystemBrowserPresenter
	stack temp[0]: 8'packageList'

{1B0A0BCC: cf 1B0A0BA9, sp 1B0A0BE4, bp 1B0A0BCC, ip 14, [] in JadeAutoSystemBrowserPresenter(JadeSystemBrowserPresenter)>>updatePresenters}
	receiver: a JadeAutoSystemBrowserPresenter

{1B0A0BA8: cf 1B0A0B89, sp 1B0A0BBC, bp 1B0A0BA4, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 41 in JadeSystemBrowserPresenter>>updatePresenters

{1B0A0B88: cf 1B0A0B65, sp 1B0A0B9C, bp 1B0A0B80, ip 3, BlockClosure>>ensure:}
	receiver: [] @ 8 in JadeSystemBrowserPresenter>>updatePresenters
	arg[0]: [] @ 41 in JadeSystemBrowserPresenter>>updatePresenters
	stack temp[0]: nil

{1B0A0B64: cf 1B0A0B49, sp 1B0A0B78, bp 1B0A0B64, ip 46, JadeAutoSystemBrowserPresenter(JadeSystemBrowserPresenter)>>updatePresenters}
	receiver: a JadeAutoSystemBrowserPresenter

{1B0A0B48: cf 1B0A0B25, sp 1B0A0B5C, bp 1B0A0B40, ip 82, [] in JadeAutoSystemBrowserPresenter(JadeSystemBrowserPresenter)>>updateCommand:onSuccessDo:}
	receiver: a JadeAutoSystemBrowserPresenter
	stack temp[0]: [] @ 3 in a CompiledExpression

{1B0A0B24: cf 1B0A0B01, sp 1B0A0B38, bp 1B0A0B1C, ip 5, Time class>>millisecondsToRun:}
	receiver: Time
	arg[0]: [] @ 54 in JadeSystemBrowserPresenter>>updateCommand:onSuccessDo:
	stack temp[0]: 45391216

{1B0A0B00: cf 1B0A0ACD, sp 1B0A0B14, bp 1B0A0AF0, ip 84, [] in JadeAutoSystemBrowserPresenter(JadeSystemBrowserPresenter)>>updateCommand:onSuccessDo:}
	receiver: a JadeAutoSystemBrowserPresenter
	stack temp[0]: [] @ 3 in a CompiledExpression
	stack temp[1]: 8'update\xapackageList\xaRimo-System\x9\xaRimo-System-\xaclassList\xaSDMigration\x9\xaclassTab\xaSDM...'
	env temp[0]: 337
	env temp[1]: 8'337\xaupdate\xapackageList\xaAnnouncements\x9ArteBar\x9Artefact-Core\x9Artefact-Examples\x9Bar...'

{1B0A0ACC: cf 1B0A0AAD, sp 1B0A0AE0, bp 1B0A0AC8, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 135 in JadeSystemBrowserPresenter>>updateCommand:onSuccessDo:

{1B0A0AAC: cf 1B0A0A89, sp 1B0A0AC0, bp 1B0A0AA4, ip 3, BlockClosure>>ensure:}
	receiver: [] @ 10 in JadeSystemBrowserPresenter>>updateCommand:onSuccessDo:
	arg[0]: [] @ 135 in JadeSystemBrowserPresenter>>updateCommand:onSuccessDo:
	stack temp[0]: nil

{1B0A0A88: cf 1B0A0A65, sp 1B0A0A9C, bp 1B0A0A80, ip 141, JadeAutoSystemBrowserPresenter(JadeSystemBrowserPresenter)>>updateCommand:onSuccessDo:}
	receiver: a JadeAutoSystemBrowserPresenter
	arg[0]: 8'update\xapackageList\xaRimo-System\x9\xaRimo-System-\xaclassList\xaSDMigration\x9\xaclassTab\xaSDM...'
	arg[1]: [] @ 3 in a CompiledExpression

{1B0A0A64: cf 1B0A0A41, sp 1B0A0A78, bp 1B0A0A60, ip 7, JadeAutoSystemBrowserPresenter(JadeSystemBrowserPresenter)>>updateCommand:}
	receiver: a JadeAutoSystemBrowserPresenter
	arg[0]: 8'update\xapackageList\xaRimo-System\x9\xaRimo-System-\xaclassList\xaSDMigration\x9\xaclassTab\xaSDM...'

{1B0A0A40: cf 1B0A0A21, sp 1B0A0A58, bp 1B0A0A3C, ip 30, JadeAutoSystemBrowserPresenter(JadeSystemBrowserPresenter)>>layoutInfo:}
	receiver: a JadeAutoSystemBrowserPresenter
	arg[0]: a Array

{1B0A0A20: cf 1B0A0A01, sp 1B0A0A34, bp 1B0A0A1C, ip 7, JadeSystemBrowser>>addSystemBrowserWithLayoutInfo:}
	receiver: a JadeSystemBrowser
	arg[0]: a Array

{1B0A0A00: cf 1B0A09D9, sp 1B0A0A14, bp 1B0A09FC, ip 86, [] in JadeSystemBrowser>>restoreLayoutAndContentsFromFile}
	receiver: a JadeSystemBrowser
	arg[0]: a Array

{1B0A09D8: cf 1B0A09B5, sp 1B0A09F4, bp 1B0A09D0, ip 11, OrderedCollection>>do:}
	receiver: a OrderedCollection
	arg[0]: [] @ 83 in JadeSystemBrowser>>restoreLayoutAndContentsFromFile
	stack temp[0]: 1

{1B0A09B4: cf 1B0A0989, sp 1B0A09C8, bp 1B0A09A4, ip 89, JadeSystemBrowser>>restoreLayoutAndContentsFromFile}
	receiver: a JadeSystemBrowser
	stack temp[0]: 8'C:\Tools\Jade\Jade System Browser Layout.stb'
	stack temp[1]: a File
	stack temp[2]: a ByteArray
	stack temp[3]: a OrderedCollection

{1B0A0988: cf 1B0A096D, sp 1B0A099C, bp 1B0A0988, ip 2, JadeSystemBrowser>>restoreLayoutAndContents}
	receiver: a JadeSystemBrowser

{1B0A096C: cf 1B0A094D, sp 1B0A0980, bp 1B0A096C, ip 10, JadeSystemBrowser>>onViewOpened}
	receiver: a JadeSystemBrowser

{1B0A094C: cf 1B0A092D, sp 1B0A0964, bp 1B0A0948, ip 7, JadeSystemBrowser(Shell)>>view:}
	receiver: a JadeSystemBrowser
	arg[0]: a ShellView

{1B0A092C: cf 1B0A0905, sp 1B0A0940, bp 1B0A0924, ip 17, JadeSystemBrowser(Shell)>>createView:}
	receiver: a JadeSystemBrowser
	arg[0]: 'Default view'
	stack temp[0]: a DesktopView

{1B0A0904: cf 1B0A08E5, sp 1B0A091C, bp 1B0A0900, ip 19, JadeSystemBrowser class(JadeShell class)>>showOnSession:}
	receiver: JadeSystemBrowser
	arg[0]: a GciSession

{1B0A08E4: cf 1B0A08C9, sp 1B0A08F8, bp 1B0A08E4, ip 4, JadeToolsToolBarPresenter>>browseClasses}
	receiver: a JadeToolsToolBarPresenter

{1B0A08C8: cf 1B0A08A9, sp 1B0A08DC, bp 1B0A08C4, ip 4, Symbol>>forwardTo:}
	receiver: browseClasses
	arg[0]: a JadeToolsToolBarPresenter

{1B0A08A8: cf 1B0A0889, sp 1B0A08BC, bp 1B0A08A4, ip 4, CommandDescription>>performAgainst:}
	receiver: a CommandDescription
	arg[0]: a JadeToolsToolBarPresenter

{1B0A0888: cf 1B0A0865, sp 1B0A089C, bp 1B0A0888, ip 14, [] in Command>>value}
	receiver: a Command

{1B0A0864: cf 1B0A0845, sp 1B0A0878, bp 1B0A0860, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 17 in Command>>value

{1B0A0844: cf 1B0A0821, sp 1B0A0858, bp 1B0A083C, ip 3, BlockClosure>>ensure:}
	receiver: [] @ 11 in Command>>value
	arg[0]: [] @ 17 in Command>>value
	stack temp[0]: nil

{1B0A0820: cf 1B0A0805, sp 1B0A0834, bp 1B0A0820, ip 22, Command>>value}
	receiver: a Command

{1B0A0804: cf 1B0A07E5, sp 1B0A0818, bp 1B0A0800, ip 30, ShellView>>performCommand:}
	receiver: a ShellView
	arg[0]: a Command

{1B0A07E4: cf 1B0A07C5, sp 1B0A07F8, bp 1B0A07E0, ip 4, JadeTranscript(Shell)>>performCommand:}
	receiver: a JadeTranscript
	arg[0]: a Command

{1B0A07C4: cf 1B0A079D, sp 1B0A07D8, bp 1B0A07B8, ip 10, CommandQuery>>perform}
	receiver: a CommandQuery
	stack temp[0]: a Command
	stack temp[1]: nil
	stack temp[2]: a JadeTranscript

{1B0A079C: cf 1B0A0779, sp 1B0A07B0, bp 1B0A0794, ip 8, DelegatingCommandPolicy(CommandPolicy)>>route:}
	receiver: a DelegatingCommandPolicy
	arg[0]: a CommandDescription
	stack temp[0]: a CommandQuery

{1B0A0778: cf 1B0A0751, sp 1B0A078C, bp 1B0A0774, ip 15, [] in ToolbarA(View)>>onCommand:}
	receiver: a ToolbarA

{1B0A0750: cf 1B0A0731, sp 1B0A0764, bp 1B0A074C, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 18 in Cursor>>showWhile:

{1B0A0730: cf 1B0A070D, sp 1B0A0744, bp 1B0A0728, ip 3, BlockClosure>>ensure:}
	receiver: [] @ 11 in View>>onCommand:
	arg[0]: [] @ 18 in Cursor>>showWhile:
	stack temp[0]: nil

{1B0A070C: cf 1B0A06E5, sp 1B0A0720, bp 1B0A0700, ip 27, Cursor>>showWhile:}
	receiver: a Cursor
	arg[0]: [] @ 11 in View>>onCommand:
	stack temp[0]: nil
	stack temp[1]: a ExternalHandle(00010003)

{1B0A06E4: cf 1B0A06C1, sp 1B0A06F8, bp 1B0A06DC, ip 17, ToolbarA(View)>>onCommand:}
	receiver: a ToolbarA
	arg[0]: a CommandDescription
	stack temp[0]: nil

{1B0A06C0: cf 1B0A0699, sp 1B0A06D4, bp 1B0A06B4, ip 18, ToolbarA(Toolbar)>>command:id:}
	receiver: a ToolbarA
	arg[0]: 0
	arg[1]: 4682
	stack temp[0]: a ToolbarButton

{1B0A0698: cf 1B0A0665, sp 1B0A06AC, bp 1B0A0680, ip 35, ContainerView(View)>>wmCommand:wParam:lParam:}
	receiver: a ContainerView
	arg[0]: 273
	arg[1]: 4682
	arg[2]: 330582
	stack temp[0]: 4682
	stack temp[1]: nil
	stack temp[2]: a ToolbarA

{1B0A0664: cf 1B0A0635, sp 1B0A0678, bp 1B0A0650, ip 23, ContainerView(View)>>dispatchMessage:wParam:lParam:}
	receiver: a ContainerView
	arg[0]: 273
	arg[1]: 4682
	arg[2]: 330582
	stack temp[0]: nil
	stack temp[1]: wmCommand:wParam:lParam:

{1B0A0634: cf 1B0A0601, sp 1B0A0648, bp 1B0A0624, ip 69, [] in InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: nil

{1B0A0600: cf 1B0A05D9, sp 1B0A0614, bp 1B0A05FC, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 79 in InputState>>wndProc:message:wParam:lParam:cookie:

{1B0A05D8: cf 1B0A058D, sp 1B0A05F4, bp 1B0A05C0, ip 84, InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: a InputState
	arg[0]: 330646
	arg[1]: 273
	arg[2]: 4682
	arg[3]: 330582
	arg[4]: 850092
	stack temp[0]: a ContainerView

{1B0A058C: cf 1B0A0565, sp 1B0A05B8, bp 1B0A0580, ip 10, ToolbarA(ControlView)>>defaultWindowProcessing:wParam:lParam:}
	receiver: a ToolbarA
	arg[0]: 514
	arg[1]: 0
	arg[2]: 655503

{1B0A0564: cf 1B0A0549, sp 1B0A0578, bp 1B0A0564, ip 12, MouseEvent(WindowsEvent)>>defaultWindowProcessing}
	receiver: a MouseEvent

{1B0A0548: cf 1B0A0529, sp 1B0A055C, bp 1B0A0544, ip 8, ToolbarA(View)>>onLeftButtonReleased:}
	receiver: a ToolbarA
	arg[0]: a MouseEvent

{1B0A0528: cf 1B0A0501, sp 1B0A053C, bp 1B0A051C, ip 9, ToolbarA(View)>>wmLButtonUp:wParam:lParam:}
	receiver: a ToolbarA
	arg[0]: 514
	arg[1]: 0
	arg[2]: 655503

{1B0A0500: cf 1B0A04D1, sp 1B0A0514, bp 1B0A04EC, ip 23, ToolbarA(View)>>dispatchMessage:wParam:lParam:}
	receiver: a ToolbarA
	arg[0]: 514
	arg[1]: 0
	arg[2]: 655503
	stack temp[0]: nil
	stack temp[1]: wmLButtonUp:wParam:lParam:

{1B0A04D0: cf 1B0A049D, sp 1B0A04E4, bp 1B0A04C0, ip 69, [] in InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: nil

{1B0A049C: cf 1B0A0475, sp 1B0A04B0, bp 1B0A0498, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 79 in InputState>>wndProc:message:wParam:lParam:cookie:

{1B0A0474: cf 1B0A0435, sp 1B0A0490, bp 1B0A045C, ip 84, InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: a InputState
	arg[0]: 330582
	arg[1]: 514
	arg[2]: 0
	arg[3]: 655503
	arg[4]: 850786
	stack temp[0]: a ToolbarA

{1B0A0434: cf 1B0A0415, sp 1B0A0454, bp 1B0A0430, ip 6, ShellView(View)>>isDialogMessage:}
	receiver: a ShellView
	arg[0]: a MSG

{1B0A0414: cf 1B0A03F5, sp 1B0A0428, bp 1B0A0410, ip 5, ShellView>>preTranslateMouseInput:}
	receiver: a ShellView
	arg[0]: a MSG

{1B0A03F4: cf 1B0A03D5, sp 1B0A0408, bp 1B0A03F0, ip 13, ShellView(View)>>preTranslateMessage:}
	receiver: a ShellView
	arg[0]: a MSG

{1B0A03D4: cf 1B0A03AD, sp 1B0A03E8, bp 1B0A03C8, ip 17, InputState>>preTranslateMessage:}
	receiver: a InputState
	arg[0]: a MSG
	stack temp[0]: 461502
	stack temp[1]: a ShellView

{1B0A03AC: cf 1B0A038D, sp 1B0A03C0, bp 1B0A03A8, ip 19, InputState>>pumpMessage:}
	receiver: a InputState
	arg[0]: a MSG

{1B0A038C: cf 1B0A0361, sp 1B0A03A0, bp 1B0A037C, ip 18, InputState>>loopWhile:}
	receiver: a InputState
	arg[0]: [] @ 9 in InputState>>mainLoop
	stack temp[0]: a MSG
	stack temp[1]: true
	stack temp[2]: [] @ 8 in Toolbar>>updateSizePosted

{1B0A0360: cf 1B0A0345, sp 1B0A0374, bp 1B0A0360, ip 15, InputState>>mainLoop}
	receiver: a InputState

{1B0A0344: cf 1B0A0329, sp 1B0A0358, bp 1B0A0344, ip 14, [] in InputState>>forkMain}
	receiver: a InputState

{1B0A0328: cf 1B0A030D, sp 1B0A033C, bp 1B0A0328, ip 13, ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry}
	receiver: a ExceptionHandler

{1B0A030C: cf 1B0A02E5, sp 1B0A0320, bp 1B0A0308, ip 22, [] in ExceptionHandler(ExceptionHandlerAbstract)>>try:}
	receiver: a ExceptionHandler

{1B0A02E4: cf 1B0A02C5, sp 1B0A02F8, bp 1B0A02E0, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 39 in ExceptionHandlerAbstract>>try:

{1B0A02C4: cf 1B0A02A1, sp 1B0A02D8, bp 1B0A02BC, ip 3, BlockClosure>>ensure:}
	receiver: [] @ 17 in ExceptionHandlerAbstract>>try:
	arg[0]: [] @ 39 in ExceptionHandlerAbstract>>try:
	stack temp[0]: nil

{1B0A02A0: cf 1B0A0279, sp 1B0A02B4, bp 1B0A0294, ip 44, ExceptionHandler(ExceptionHandlerAbstract)>>try:}
	receiver: a ExceptionHandler
	arg[0]: [] @ 10 in InputState>>forkMain
	stack temp[0]: nil
	stack temp[1]: a Process('Main' base 1B0A0000* in SessionManager>>logError: sp=00000000 ip=4 list=02760010)
	env temp[0]: nil

{1B0A0278: cf 1B0A0255, sp 1B0A028C, bp 1B0A0270, ip 7, BlockClosure>>on:do:}
	receiver: [] @ 10 in InputState>>forkMain
	arg[0]: ProcessTermination
	arg[1]: [] @ 13 in BlockClosure>>newProcess

{1B0A0254: cf 00000001, sp 1B0A0268, bp 1B0A0254, ip 17, [] in BlockClosure>>newProcess}
	receiver: [] @ 10 in InputState>>forkMain
