### ISSUE TITLE
Save a package as FileTree from System Browser

### ISSUE THREAD

**Issue by brunobuzzi** [jgfoster/Jade.bak#165]
In the latest version the Package tab is missing from System Browser.  From this tab was possible to save a Packge as File Tree in order to upload it to github.
This was an awesome feature.

**Comment by brunobuzzi** [comment]
The problem is that `GciSession>>isPackagePolicyEnabled` is `false`

**Comment by brunobuzzi** [comment]
The problem is that `GciSession>>isPackagePolicyEnabled` is `false`

**Comment by jgfoster** [comment]
That change certainly wasn't intended! This probably explains #162. I should have it figured out soon.
