### ISSUE TITLE
Jade2.2.7 ... when I login initially as a user with no code mod privileges I get a Transcript window that I cannot close ... after the security error

### ISSUE THREAD

**Issue by dalehenrich** [jgfoster/Jade.bak#170]
![image](https://user-images.githubusercontent.com/623951/44364366-a4588f00-a47b-11e8-981a-be3d07e8a3f6.png)

Here's the version information in case it matters:
![image](https://user-images.githubusercontent.com/623951/44364403-c4884e00-a47b-11e8-9933-eb868c00bba7.png)

**Comment by dalehenrich** [comment]
I've already close the Jade console ... so how do i get rid of this extra window ... reboot?

**Comment by dalehenrich** [comment]
I've already close the Jade console ... so how do i get rid of this extra window ... reboot?

**Comment by dalehenrich** [comment]
... I **can** confirm that rebooting does close the window:)

**Comment by jgfoster** [comment]
Attempting to check for dirty objects failed. Now we just ignore the error and continue the logout.
