### ISSUE TITLE
Jade2.2.7 - Find class in dictionary browser logged in as SystemUser in extent0.dbf ... MNU

### ISSUE THREAD

**Issue by dalehenrich** [jgfoster/Jade.bak#171]
```
a MessageNotUnderstood occurred (error 2010), a ClassOrganizer class does not understand  
---
MessageNotUnderstood >> defaultAction @2 line 3
MessageNotUnderstood (AbstractException) >> _signalWith: @5 line 25
MessageNotUnderstood (AbstractException) >> signal @2 line 47
ClassOrganizer class (Object) >> doesNotUnderstand: @9 line 10
ClassOrganizer class (Object) >> _doesNotUnderstand:args:envId:reason: @7 line 12
SystemOrganizer >> categoryDict @3 line 3
JadeServer64bit32 (JadeServer) >> sbFindClassPackageMap @18 line 8
JadeServer64bit32 (JadeServer) >> sbFindClass @2 line 4
JadeServer64bit32 (JadeServer) >> _systemBrowserCommand @109 line 34
[] in  ExecBlock0 (JadeServer) >> systemBrowserA: @14 line 10
Time class >> secondsElapsedTime: @5 line 11
Time class >> millisecondsElapsedTime: @2 line 6
JadeServer64bit32 (JadeServer) >> _millisecondsElapsedTime: @2 line 3
JadeServer64bit32 (JadeServer) >> systemBrowserA: @2 line 4
JadeServer64bit32 (JadeServer) >> systemBrowser: @3 line 3
[] in  ExecBlock0 (JadeServer64bit) >> systemBrowser: @2 line 4
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
JadeServer64bit32 (JadeServer64bit) >> systemBrowser: @2 line 5
GsNMethod class >> _gsReturnToC @1 line 1
```

**Comment by jgfoster** [comment]
What version of GemStone is this?
What is the source code for SystemOrganizer>>categoryDict (particularly step point 3 on line 3)?
Where did SystemOrganizer come from? It isn't in a base 2.4.6 or 3.4.2 repository!

**Comment by jgfoster** [comment]
JadeServer>>sbFindClassPackageMap is explicitly checking to verify that ClassOrganizer is visible (if not, we return an empty Dictionary). So, there is a situation in which the ClassOrganizer is present (with Monticello?), and the behavior of that class has changed.

**Comment by dalehenrich** [comment]
This series of errors (#170, #171,#173,#174) were all submitted when you suggested that exporting JadeServer and loading it permanently in the system would be a workaround for a customer using 3.2.15 and Jade for viewing code in their production dB ... to record the follow in errors that occurred when following your instructions ... this was done in case the customer went the route if using Jade for this purpose .. all of these issues were showstoppers ... at the end of the day we addresses these and other issues in Jadeite ...

**Comment by jgfoster** [comment]
@dalehenrich , thanks for the update. The JadeServer filein issue should have been addressed by #130.

**Comment by dalehenrich** [comment]
@jgfoster ... we were using the technique described in #130 when we hit this bug ...

**Comment by jgfoster** [comment]
This suggests that there is a version of SystemOrganizer or ClassOrganizer that is different from the one in seaside.extent0.dbf. I'll leave this closed but with the understanding that the bug is not fixed.

**Comment by dalehenrich** [comment]
IIRC, the MNYU was for `cachedOrganizer` which is not in an extent0.dbf repo ... don't know why that information didn't show up in the stack, pilot error with copy/paste most likely
