### ISSUE TITLE
Error in MethodListBrowser

### ISSUE THREAD

**Issue by obi068** [jgfoster/Jade.bak#178]
I often get the following debug if i change a method in the MethodListBrowser and select the same method again.
GS 3.4.0, Jade 2.2.6
![image](https://user-images.githubusercontent.com/1876280/45053161-741f0c00-b089-11e8-999e-7e1d18aae966.png)

And also this error

![image](https://user-images.githubusercontent.com/1876280/45053254-bf391f00-b089-11e8-8473-5846aaae39ea.png)

**Comment by jgfoster** [comment]
I haven't been able to identify the problem but I've added some debugging information to v2.2.8 and would like to see the stack when it happens again. Thanks!

**Comment by obi068** [comment]
Jade 2.2.8.
Same stack as before!

![image](https://user-images.githubusercontent.com/1876280/45072223-55953100-b0da-11e8-94c4-e3ea773ea9c4.png)

**Comment by jgfoster** [comment]
More debugging in v2.2.9 (forthcoming).

**Comment by obi068** [comment]
New debugs using V2.2.9

[Jade.ERRORS.txt](https://github.com/jgfoster/Jade/files/2488750/Jade.ERRORS.txt)

**Comment by obi068** [comment]
Now with Jade.log
[Jade.log](https://github.com/jgfoster/Jade/files/2490453/Jade.log)
[Jade.ERRORS1.txt](https://github.com/jgfoster/Jade/files/2490454/Jade.ERRORS1.txt)
