### ISSUE TITLE
2.2.7 - Browser, Implementors of selected method not available any more

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade.bak#180]
I am still having this issue (Jade 2.2.7 against GS 3.4.0) - and it seems to work in the Method List Browser, but not in the System Browse. The menu entries simply do not appear - but it does not seem to be that sample.
When I switched to the Method List Browser I noticed, that the menu appears, then switched back to System browse and then suddenly the menues appears there also - and after a restart (of jade) it was still there ... something is wrong there, but do not know what.

**Comment by jgfoster** [comment]
So after a restart of Jade the menus are present? Are you able to recreate the situation in which the menus are missing?

**Comment by feldti** [comment]
This is still not working. I am now using 2.3.1 under Windows/VirtualBox (due to the WINE problems) under Linux and the menu entry is sometimes coming and very often not coming.

Pretty bad

**Comment by feldti** [comment]
Ha, I know now what has happening to me: I normally put the cursor in the method name in the source code and then do a pop-up menue.
Sometimes this does not work - then I have to put the cursor before the method name and then it seems to work.

**Comment by jgfoster** [comment]
The details help. Is the method name a keyword method name? If so, is the failing case when the cursor is in the second or subsequent keyword? That is known not to work. Or is it in the first keyword? That should work. Is the keyword underlined? When you hover over an underlined keyword does it show the step point as a tool tip? If you can reproduce a case that involves base classes then it would be easier for me to investigate.

**Comment by feldti** [comment]
I think it always works if I look for the step point and then try to activate the Pop-Up menu. From that on I had no problems using this feature. Sometimes I got the impression, that in message like "self ..." the step point is more toward self than towards the message itself.

For me this is now ok ansd you may close it

**Comment by jgfoster** [comment]
Thanks.
