### ISSUE TITLE
Repository cleanup

### ISSUE THREAD

**Issue by jgfoster** [jgfoster/Jade.bak#186]
For a long time I was including executables and zip files in the checkin rather than using the releases feature of Github. It would be nice to do some cleanup and [this](https://rtyley.github.io/bfg-repo-cleaner/) was suggested.

**Comment by dalehenrich** [comment]
The article on BFG doesn’t mention what happens to GitHub forks (at least I didn’t see any mentions) when this done ...  

The quote “best to delete old clones” makes me wonder, but I am by no means an authority ...

**Comment by jgfoster** [comment]
I've moved the 877 MB repository to Jade.bak and started a new one with the saved history (weighing in at 206 MB for starters!). I've transferred the open issues and written to those with immediate forks. So I think this is done.
