### ISSUE TITLE
Object inspector breadcrumbs

### ISSUE THREAD

**Issue by thelliez** [jgfoster/Jade.bak#187]
This has been an minor issue for me for a while, but it became major while trying to debug a complicated situation.

When inspecting an object, the drill-down works great.  But trying to get to the 'Previous Object' with the left green arrow does not return to the expected object.

Updating to the latest 2.2.8 did not solve the issue.  Gemstone/S 3.3.6 in the backend.

Jade runs in Windows 10 (with VMWare Fusion on a Mac).

Thanks!
Thierry

**Comment by brunobuzzi** [comment]
Do you have a test case for this ? I implemented this inspector for Jade but it works fine. If you provide a step by step to reproduce it i will look into it.

**Comment by brunobuzzi** [comment]
One thing it should be mention is that arrows works in circular fashion. If you reach the latest object an press right arrow --> you go to first object. If you are in first object and press left arrow you go to last object. If you press the red X button --> the current object is removed from navigation.

**Comment by thelliez** [comment]
Sorry for the delay.  

With 2.2.8, it happens all the time...  I click on an Array, then an object in this array, good so far.  

But then if I click back twice and try to click forward (right) again,  the inspector gets lost (and me too ;-).  It works fine drilling down, but any attempt to go back up more than one level seems to be losing its track.  That seems to happen with any sort of Collections.

I am expecting that clicking on the left arrow multiple times will eventually get back to the starting object, but that's not the case.  Often it goes in some some of infinite loop that does not make sense (to me).

**Comment by brunobuzzi** [comment]
I think the problem you are seeing is the circular behavior. If you have N objects in the inspector and you are inspecting the first object and then click on left arrow you go to the object N (and viceversa).
This can behavior can be removed i do not  know what @jgfoster think about this.
The following methods should be changed at `JadeNavigationInspector`:
`JadeNavigationInspector>>queryCommand:`
`JadeNavigationInspector>>getNextObject`
`JadeNavigationInspector>>getPreviousObject`
If @jgfoster approves the change i will create the Pull Request.

**Comment by jgfoster** [comment]
I would prefer the non-circular model; it seems much more intuitive to me.

**Comment by brunobuzzi** [comment]
I have open a PR that fix circular navigation but i do not know if address @thelliez problem (see PR comments)
https://github.com/jgfoster/Jade/pull/189
