### ISSUE TITLE
Pretty strange behaviour ...

### ISSUE THREAD

**Issue by MFeldtmann** [jgfoster/Jade.bak#19]
selectedFrame 

```
...
(frame := gsProcess frameForLevel: index) isNil ifTrue: [^self].
```

**Comment by MFeldtmann** [comment]
Strange things are happening. Working now with 3.2.9 I get (perhaps with earlier versions also) strange errors. The following method fails (index = 4) and returns not nil, but a class ....

JadeDebugger>>selectedFrame 

```
...
(frame := gsProcess frameForLevel: index) isNil ifTrue: [^self].
    ...
```

**Comment by jgfoster** [comment]
Marten,
Please try again after unchecking the "Open new socket..." checkbox on the Advanced tab of Jade Login Shell.
James

**Comment by jgfoster** [comment]
I believe that this issue has been addressed.

**Comment by jgfoster** [comment]
I'll close this since it appears to be related to the experimental socket protocol (which I should probably hide or remove).
