### ISSUE TITLE
extraneus characters appended during fileout in 3.4.2

### ISSUE THREAD

**Issue by alexkogan** [jgfoster/Jade.bak#190]
causes topaz command error 
input $l2tests/ernie/LostCacheRemoteTest.gs
topaz 1> ï»¿! -------------------

**Comment by jgfoster** [comment]
Although Topaz recognizes UTF-8, it does not properly handle the "Byte Order Mark" at the beginning of a UTF-8 file (
http://kermit.gemtalksystems.com/bug?bug=47665). The work-around is to use Notepad++ to remove the BOM (see https://stackoverflow.com/questions/32986445/remove-a-bom-character-in-a-file).

**Comment by alexkogan** [comment]
topaz is main consumer of file outs from Jade as such it makes it significant impairment. Editing every file every time is totally impractical. Even if future topaz will include full support for BOM older version are everywhere. 32 bit notwithstanding. They won't work with UTF8 either I believe. For very least supporting option of 7bit chars or UTF8 would be nice
