### ISSUE TITLE
Jade 2.3.2: greaterThanInteger Error-Dialog after Login

### ISSUE THREAD

**Issue by PeterMoe** [jgfoster/Jade.bak#193]
Hello,

I am using Gemstone 2.4.6 and Jade 2.3.2. About 20-30 sec after login to DB and doing nothing(only waiting) I get a error dialog with String: 

GsDoesNotUnderstand does not understand #greaterThenInteger:

![greaterthaninteger_error](https://user-images.githubusercontent.com/40350726/51597990-dd9a9c80-1efc-11e9-875a-e1e4451a0687.JPG)

**Comment by jgfoster** [comment]
Here is an example of a similar error:

{1F7803B8: cf 1F780399, sp 1F7803CC, bp 1F7803B4, ip 4, GsFatalError(Object)>>doesNotUnderstand:}
	receiver: a GsFatalError
	arg[0]: Message selector: greaterThanInteger: arguments: 020746E0

{1F780398: cf 1F780379, sp 1F7803AC, bp 1F780394, ip 4, SmallInteger>><}
	receiver: 0
	arg[0]: a GsFatalError

{1F780378: cf 1F78034D, sp 1F78038C, bp 1F780368, ip 76, GciSession>>heartbeat:arguments:}
	receiver: a GciSession
	arg[0]: a OopType64
	arg[1]: a OopType64Array
	stack temp[0]: a GsFatalError
	stack temp[1]: nil

{1F78034C: cf 1F780329, sp 1F780360, bp 1F780344, ip 20, [] in GciSession>>startHeartbeat}
	receiver: a GciSession
	stack temp[0]: a OopType64
	stack temp[1]: a OopType64Array

**Comment by jgfoster** [comment]
Peter,

It would be helpful to see a copy of the stack for this error. Starting with Jade v2.3.3 there is a menu command, Jade Login Window -> Help -> Open Executable Directory. From there you should be able to find Jade.ERRORS. Open that in a text editor and find the most recent error. Select up to a dozen or so of the frames that are at and below the #doesNotUnderstand: and paste them as a comment.

Thanks,
James

**Comment by jgfoster** [comment]
The current version of Jade silently ignores any errors received during the heartbeat. I think that this is better than strange errors.
