### ISSUE TITLE
Method categories can fail to show in System Browser (v2.3.5)

### ISSUE THREAD

**Issue by PeterMoe** [jgfoster/Jade.bak#204]
Hello,

found a other constellation.
The first time when I open the System Browser, klick on a entry in packages-tap, klick on class in tap Hierarchy, categories-tap is empty.

![pic01](https://user-images.githubusercontent.com/40350726/53087506-a7563a00-3507-11e9-97fb-d073c18643c6.jpg)

**Comment by jgfoster** [comment]
Hello Peter,

While I've submitted what I believe is a fix for the original problem I haven't built a new runtime. If you are running a development version then you can pull the latest and see the fix. Otherwise you will need to wait for 2.3.6 in order to see the fix.

James

**Comment by jgfoster** [comment]
Peter,

Could you try again with v2.3.6 and let me know if this repeats?

James

**Comment by PeterMoe** [comment]
Hi James,

In v2.3.6 bug is gone, thanx. :-)

Peter
