### ISSUE TITLE
Compile errors are not being reported in the System Browser

### ISSUE THREAD

**Issue by obi068** [jgfoster/Jade.bak#207]
I dont get any warnings e.g. like undefined symbol in the code editor if i save a method.
If i do a commit afterwards all my changes are lost.

**Comment by jgfoster** [comment]
I believe this was recently introduced by the logging of server errors. I consider it a high priority and will try to have a fix in the next 48 hours.

**Comment by jgfoster** [comment]
This should be fixed in v2.3.7.
