### ISSUE TITLE
1.088+: Loading Monticello Packages do not load any more

### ISSUE THREAD

**Issue by MFeldtmann** [jgfoster/Jade.bak#21]
I have problems loading monticello packages via "Browser Monticello Repositories". I'm working on a package adding some methods, do a commit. Then I decide to load another version of that package via this Window and I am asked (via the usual dialog), if the changes made in this package can be thrown away: I answer yes - and then I get an "a ImproperOperation occured (error 2717) nil" dialog. (if pressing no: I get this error dialog also)

Did the same work with 1.086 and it worked without problems.

**Comment by jgfoster** [comment]
Thanks for the report and let me know if you have this or other issues.
