### ISSUE TITLE
Annoying Busy Cursors appears

### ISSUE THREAD

**Issue by MFeldtmann** [jgfoster/Jade.bak#22]
Why do I get (quite often) these annoying busy cursors when switching Windows within Jade

**Comment by jgfoster** [comment]
I've struggled with that for some time (years). I've got code that is supposed to change the cursor back after a GemStone operation, but somehow it gets missed sometimes. As a work-around, there is a "Reset Cursor" method on the Transcript's File menu that I find I use with some regularity. In any case, I'll leave this open and continue the investigation.

**Comment by baderth** [comment]
No resolution here, but a workaround: 
I've replaced the GS cursor icons within the icons folder with dead simple mouse cursor icons, that way, even if the cursor gets stuck, its just a normal mouse-cursor. (find my cursors attached)

[icons.zip](https://github.com/jgfoster/Jade/files/1000268/icons.zip)

**Comment by jgfoster** [comment]
I believe that this is fixed with 10ec2185e47f54101d8226d8bb16cfd6bf1e898f.
