### ISSUE TITLE
Commit failed

### ISSUE THREAD

**Issue by obi068** [jgfoster/Jade.bak#224]
Since version 2.3.11 (Gemstone 3.4.0) we always get commit failed
after a few seconds, also if i do not change anything.

Some suspicous entry in the transactionConflict dictionary.:

![image](https://user-images.githubusercontent.com/1876280/62289607-75a2b100-b45f-11e9-8df5-4a1ec7d35153.png)

**Comment by obi068** [comment]
It only happens if 2 users are working with Jade on the same database.

**Comment by PeterMoe** [comment]
Hi James,
i have the same Problem here, working with more then one Session in same database is not possible.
Every time one Session commit the other Session get Commit failed.

The transaction conflict happens in:
`JadeServer --> _describeMethod:`
when i commet the last line out:
`UserGlobals at: #'James' put: 'h' -> writeStream contents.`

It fix the transaction conflicts: Session one and Session two can now work without any conflicts.
I dont see any side effects in working with jade, when i comment it out.
You have the writeStream as an instance variable on JadeServer, why do you want to save it in UserGlobals ?

And I haven't found any senders to this Dictionary too.

Regards,
Peter

**Comment by jgfoster** [comment]
This was debugging code that should not have been left in for production. See #221.
