### ISSUE TITLE
Closeing SystemBrowser to fast with unsaved changes some errors

### ISSUE THREAD

**Issue by PeterMoe** [jgfoster/Jade.bak#227]
Hello James,

i have found some problems with "to fast closeing the System Browser with unsaved changes", if the Server takes to long for responds and i close the the System Browser to fast.

1. "updateMethodFilter" --> Wrong position of readStream
-  if "updateSuperclassList" exit with ^self" method "updateMethodFilter" ist at the wrong position in the readSteam.
2. "updateMethod" --> get MessageBox 'Copy changes to clipboard?' 2 times and an Jade Error
- Reason: if SystemBrowser is closed and the updateMethod is called in background "methodSourcePresenter view isModified" responds a DeafObject, this object evaluate the trueBlock but is not true.
3. "updateMethod" --> detect: Error
- code: "textAreaTabs subViews detect: [:each | each class == TabViewXP]" because the view is closed we don't find a object with class == TabViewXP, get error because no Object found with detect. (missing the ifNone: block)

i have "correct" the "wrong reaction of a dead SystemBrowser", now it works without Errors but i don't know if you like my solution. ;-)

I will modify my pull request, shortly.

Regards,
Peter

**Comment by jgfoster** [comment]
I believe the fix for this has been merged.
