### ISSUE TITLE
SystemBrowser MenuBar menu wrong behavior

### ISSUE THREAD

**Issue by PeterMoe** [jgfoster/Jade.bak#232]
Hello James,

StepPoints wil not only updated in Edit menu, it also updates the first four Menus in MenuBar of JadeSystemBrowser.

![MultiEntry](https://user-images.githubusercontent.com/40350726/63002404-2785a880-be76-11e9-91a6-a0115931f5dd.png)

this only happens when step point is 1.

Regards,
Peter

**Comment by PeterMoe** [comment]
Hi James,

i check if menu ihave text "&Edit" if true make menuBreakPoint:

Regards,
Peter

**Comment by jgfoster** [comment]
That was indeed weird! Thanks. I believe the fix for this has been merged.
