### ISSUE TITLE
Method source German characters changes indicators Position

### ISSUE THREAD

**Issue by PeterMoe** [jgfoster/Jade.bak#233]
Hello James,

i use Gemstone 2.4.6, when I open methods with german characters i have an offset of indicators for methods.

![indicatorOffset](https://user-images.githubusercontent.com/40350726/63003314-29e90200-be78-11e9-9849-0c758b9fb522.png)

Regards,
Peter

**Comment by PeterMoe** [comment]
Hello James,

the Issue is, that gemstone 2.4.6 only have ansi string method sources and no UTF8 so the StepPoints for german character ( ö ) is ansi 1 point but in utf8String 2 points.

Jade uses UTF8String as Source, so all not ascii characters get i more point.

I collect the indexes of non ascii characters (for utf8 we get 2 indexes per non ascii character) and added ( found indexes size before start postion / 2 ) to the "range start" as offset for the indicators.

for gemston 2.4.6 it works

![indicatorOffset_correct](https://user-images.githubusercontent.com/40350726/63006382-ba2a4580-be7e-11e9-84c9-a597873adca3.png)

I don't know if gemstone > 2.4.6 have utf8 step-points in method source so i identify the used library and implemented the correction on JadeServerClass.

Regards,
Peter

**Comment by jgfoster** [comment]
I believe the fix for this has been merged.
