### ISSUE TITLE
Error when stoneNRS does not have stoneName

### ISSUE THREAD

**Issue by brunobuzzi** [jgfoster/Jade.bak#249]
Error 3 out of bound.
I think this was introduced by latest Dolphin changes to fix:
https://github.com/dolphinsmalltalk/Dolphin/issues/877

`GciSession>>initializeLibrary:stoneNRS:gemNRS:userID:password:hostUserID:password:initials:debugPath: `
This method should be updated with:
	`stoneNRS := String withAll: stoneString.`
I will try to generate a PR as soon as possible

**Comment by jgfoster** [comment]
Is this in GciSession>>titleBarFor: where we attempt to get the stone name? If so, do you have a login without a stone name? What is the stoneNRS value? How many $! characters in it?

**Comment by jgfoster** [comment]
Bruno reports that this is no longer an issue.
