### ISSUE TITLE
Unable to login for Jade development under Win10 and latest Dolphin

### ISSUE THREAD

**Issue by brunobuzzi** [jgfoster/Jade.bak#250]
- Latest Dolphin
- Win10
- Only happen inside Dolphin image (Jade.exe works ok)

When try to login i got the following error (this not happen with Jade.exe):
![image](https://user-images.githubusercontent.com/4719282/80847769-36201580-8be7-11ea-9a18-a7bda8540b12.png)

**Comment by brunobuzzi** [comment]
Walkback:
1/5/2020 20:19:00: 'Invalid access to memory location. Reading 0xCD7000, IP 0x5E72B9C2 (C:\Users\bruno\Documents\GitHub\Dolphin\JadeForBPM\bin\libgcirpc-3.5.1-32.dll)'
ProcessorScheduler>>gpFault:
[] in ProcessorScheduler>>vmi:list:no:with:
BlockClosure>>ifCurtailed:
ProcessorScheduler>>vmi:list:no:with:
LibGciRpc64_3_5_1(LibGciRpc64_3_3_0)>>gciNbExecuteStrFromContextDbg_:_:_:_:_:_:_:
[] in LibGciRpc64_3_5_1(LibGciRpc64_3_3_0)>>session:execute:context:environment:
[] in LibGciRpc64_3_5_1(GciSingleThreadedLibrary)>>activity:critical:
BlockClosure>>ifCurtailed:
[] in LibGciRpc64_3_5_1(GciSingleThreadedLibrary)>>activity:critical:
ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>on:do:
LibGciRpc64_3_5_1(GciSingleThreadedLibrary)>>activity:critical:
LibGciRpc64_3_5_1(LibGciRpc64_3_3_0)>>session:execute:context:environment:
GciSession>>_executeString:fromContextOop:environment:
[] in GciSession>>executeString:fromContext:environment:
[] in GciSession>>returningResultOrErrorDo:
ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>on:do:
GciSession>>returningResultOrErrorDo:
GciSession>>handlingClientForwarderSendDo:
[] in GciSession>>withExplanation:doA:
ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>on:do:
[] in GciSession>>withExplanation:doA:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
[] in GciSession>>withExplanation:doA:
ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>on:do:
[] in BlockClosure>>newProcess:

**Comment by jgfoster** [comment]
I've reproduced it and am investigating...

**Comment by brunobuzzi** [comment]
I think is a problem with Dolphin latest version because i generate an .EXE with new Dolphin and i got a similar error as in the image.
1:01:54 AM, 5/2/2020: Invalid access to memory location. Reading 0x1A4000, IP 0x5E58B9C0 (C:\Users\bruno\Documents\GitHub\Dolphin\JadeForBPM\runtime\bin\libgcirpc-3.5.1-32.dll)

**Comment by brunobuzzi** [comment]
James,
The problem arise when generating Jade image from scratch.
Because i just copied Jade project from my old notebook to the new notebook and Jade worked ok.

So it seems a problem with the new Dolphin image and the new Dolphin VM seems to work ok with "old" images.

**Comment by brunobuzzi** [comment]
After a more deep research Jade works with Dolphin:
https://github.com/dolphinsmalltalk/Dolphin/tree/bcee95ee0fb0e7ec99b6ef682d082437ff8f9b97

After this commit Jade start to fail to login with "Invalid access to memory location"

**Comment by jgfoster** [comment]
Bruno, 
Excellent research! I've confirmed that Jade can log in with bcee95ee0fb0e7ec99b6ef682d082437ff8f9b97 but the login fails with f3cce4ebaded8de71b90ca2eccff4b3b77ba1928. For now, I'll build with the 27-Nov-2019 commit for Dolphin, and keep this open to investigate further. I'll also put a comment in the Dolphin project.
