### ISSUE TITLE
Handle trailing empty elements returned by String>>#'subStrings:'

### ISSUE THREAD

**Issue by brunobuzzi** [jgfoster/Jade.bak#254]
EDIT by @jgfoster:  See [Dolphin #877](https://github.com/dolphinsmalltalk/Dolphin/issues/877).

With latest Jade when searching classes a walkback arise. 
It seems that the first class of the list is empty:
![imagen](https://user-images.githubusercontent.com/4719282/80924780-5247c200-8d61-11ea-80c2-8cdf4bea908b.png)

3/5/2020 17:12:29: 'Index 4 is out of bounds'
Array(Object)>>errorSubscriptBounds:
Array(Object)>>_primitiveError:at:
Array(ArrayedCollection)>>at:
[] in UndefinedObject>>{unbound}doIt
ListViewColumn>>contentFromRow:
ListViewColumn>>textFromRow:
ListView>>onDisplayDetailsRequired:
ListView(IconicListAbstract)>>nmGetDispInfoW:
ListView>>nmNotify:
DialogView(View)>>wmNotify:wParam:lParam:
DialogView(View)>>dispatchMessage:wParam:lParam:
[] in InputState>>wndProc:message:wParam:lParam:cookie:
BlockClosure>>ifCurtailed:
GuiInputState(InputState)>>wndProc:message:wParam:lParam:cookie:
ListView(ControlView)>>defaultWindowProcessing:wParam:lParam:
ListView(ControlView)>>wmPaint:wParam:lParam:
ListView(View)>>dispatchMessage:wParam:lParam:
[] in InputState>>wndProc:message:wParam:lParam:cookie:
BlockClosure>>ifCurtailed:
GuiInputState(InputState)>>wndProc:message:wParam:lParam:cookie:
ProcessorScheduler>>unwindCallback:
[] in InputState>>wndProc:message:wParam:lParam:cookie:
[] in BlockClosure>>ifCurtailed:
BlockClosure>>ifCurtailed:
GuiInputState(InputState)>>wndProc:message:wParam:lParam:cookie:
ListView(ControlView)>>defaultWindowProcessing:wParam:lParam:
ListView(View)>>dispatchMessage:wParam:lParam:
[] in InputState>>wndProc:message:wParam:lParam:cookie:
BlockClosure>>ifCurtailed:
GuiInputState(InputState)>>wndProc:message:wParam:lParam:cookie:
ListView(ControlView)>>defaultWindowProcessing:wParam:lParam:
ListView(View)>>dispatchMessage:wParam:lParam:
[] in InputState>>wndProc:message:wParam:lParam:cookie:
BlockClosure>>ifCurtailed:
GuiInputState(InputState)>>wndProc:message:wParam:lParam:cookie:
ListView(ControlView)>>defaultWindowProcessing:wParam:lParam:
ListView(View)>>dispatchMessage:wParam:lParam:
[] in InputState>>wndProc:message:wParam:lParam:cookie:
BlockClosure>>ifCurtailed:
GuiInputState(InputState)>>wndProc:message:wParam:lParam:cookie:
GuiInputState(InputState)>>pumpMessage:
GuiInputState(InputState)>>loopWhile:
GuiInputState(InputState)>>mainLoop
[] in GuiInputState(InputState)>>forkMain
ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>on:do:

**Comment by brunobuzzi** [comment]
Jade tools with out of bound error:
* Search classes
* Browser users
* Open Monticello Browser
* Browse Processes
Update (the following also does not work):
* Browse Implementors
* Browse Senders
Update 2:
It seems a general problem with `subStrings:` that answer collections with its last element an empty string.

**Comment by jgfoster** [comment]
Yes, I think that was the problem you identified with a different issue. As mentioned in [Dolphin #877](https://github.com/dolphinsmalltalk/Dolphin/issues/877), "Note that fixing this is a breaking change"!

We have several options:
* revert to an earlier version of Dolphin (not a good long-term solution!)
* implement our own version of #'subStrings:' (#'nonEmptySubStrings:' ?) that has the old behavior (and modify all the senders)
* strip off empty elements after sending #'subStrings:' 
* not add a separator at the end of an element (unless there is a new element)
@brunobuzzi, Any preferences?

**Comment by brunobuzzi** [comment]
@jgfoster i was thinking on option 2) a new method and modify senders. I can do the change and send a PR by tomorrow. `nonEmptySubStrings:` is ok

**Comment by jgfoster** [comment]
I agree. When I was writing out the options I assumed that option 2 would be wrong (fighting against how the base image works). But after thinking about it for a few minutes, it actually is a very "intention-revealing-selector" and seems to reduce the duplicate code in option 3. Option 4 would make the code that creates the strings unnecessarily complicated. So, yes, please feel free to take this on. 

Note that not all senders would need this; it will take a bit of reading of code to tell which ones (but should be fairly obvious).

**Comment by jgfoster** [comment]
@brunobuzzi, I'm starting to have some second thoughts about this. I have another (small and proprietary) Dolphin app that I'm updating and it turns out that sometimes an empty element will be proper as a _non-final_ element. For example, 'aa::bb:' used to come out as #('aa' '' 'bb'). The new Dolphin behavior is #('aa' '' 'bb' '') but our approach gives #('aa' 'bb') which is even worse. 

In my other project I've implemented the (unwieldy) selector #'subStringsTrimmingTrailingEmptyElement:' (more intention-revealing than #'subStringsA:' or #'subStringsLegacy:') as more explicitly backwards compatible. I'm worried not just about losing empty fields, but shifting everything else up. 

Thoughts?

**Comment by brunobuzzi** [comment]
@jgfoster well i think `nonEmptySubStrings:` too good intention-revealing-selector so i implemented just that :)
`subStringsTrimmingTrailingEmptyElement:` is another good name. I will send a PR replacing  `nonEmptySubStrings:` with `subStringsTrimmingTrailingEmptyElement:` (trimming only the last element if it is empty).
Also think that Blair should not changed this method instead create a new one but we all can argue which way is better all day long :)

**Comment by jgfoster** [comment]
I believe this is working properly now. Thanks!
