### ISSUE TITLE
Autocompletion registry in Jade options is not working with latest Dolphin

### ISSUE THREAD

**Issue by brunobuzzi** [jgfoster/Jade.bak#257]
Checking this issue now...
There is a missing method:
JadeAutoCompletationRegistryPreference>>publishedAspects
```
publishedAspects
	"Answer a <LookupTable> of the <Aspect>s published by the receiver."
	| aspects |
	aspects := super publishedAspects.
	aspects
		add: (Aspect collection: #variableMap);
		add: (Aspect collection: #paramMap);
		add: (Aspect collection: #registry).
	^aspects
```
When the pending PR is processed i will create another PR with this code.

**Comment by jgfoster** [comment]
This method is present in the current Jade source and appears to have been added in June. See https://github.com/jgfoster/Jade/commit/4c40e3c3c1f2b674bfee696032fffe873af21ae7.
