### ISSUE TITLE
2.0.5 not that stable any more ...

### ISSUE THREAD

**Issue by MFeldtmann** [jgfoster/Jade.bak#26]
I've seen here several crashes of Jade 2.0.5 in regular cases each day, where an error dialog pops up several times - as if an exception is thrown (in c) and terminates the whole application.

This happens very often, when I get the error dialog: "Sorry, we are not yet prepared to convert a CodeSourcePresenter to an OOP !" after I try to inspect an expression and this expression is faulty.

**Comment by jgfoster** [comment]
Is there an error log adjacent to the executable? If so, could you copy a stack or two and submit it? 

I've just tested inspecting an expression in a workspace and if the expression is good then I get an inspector and if the expression is faulty I get a walkback showing the error.

**Comment by jgfoster** [comment]
Based on lack of follow-up, I'm going to close this. Please feel free to re-open or create a new issue if there are continuing issues.
