### ISSUE TITLE
Jade fails to start due to XML error even after deleting layout files

### ISSUE THREAD

**Issue by alexkogan** [jgfoster/Jade.bak#262]
Latest version
![image](https://user-images.githubusercontent.com/1958382/87210544-c1461780-c2ca-11ea-9278-21210d49193f.png)

************************** Dolphin Virtual Machine Dump Report ***************************

16:29:10 PM, 7/10/2020: Error parsing XML text - 'Invalid at the top level of the document.' at 1, 1

*----> VM Context <----*
Process: {20EA0210:size 239 words, suspended frame 20EA24C5, priority 5, callbacks 0, FP control 80007, thread 00000000}
Active Method: SessionManager>>logError:
IP: 02525F19 (9)
SP: 20EA06AC
BP: 20EA0680 (269)
ActiveFrame: {20EA0684: cf 20EA0665, sp 20EA069C, bp 20EA0680, ip 5, JadeSessionManager(SessionManager)>>logError:}
	receiver: a JadeSessionManager
	arg[0]: a DOMParseError

New Method: VMLibrary>>dump:path:stackDepth:walkbackDepth:
Message Selector: dump:path:stackDepth:walkbackDepth:

*----> Stack Back Trace <----*
{20EA0684: cf 20EA0665, sp 20EA069C, bp 20EA0680, ip 5, JadeSessionManager(SessionManager)>>logError:}
	receiver: a JadeSessionManager
	arg[0]: a DOMParseError

{20EA0664: cf 20EA0645, sp 20EA0678, bp 20EA0660, ip 3, JadeSessionManager(SessionManager)>>unhandledException:}
	receiver: a JadeSessionManager
	arg[0]: a DOMParseError

{20EA0644: cf 20EA0625, sp 20EA0658, bp 20EA0640, ip 3, JadeSessionManager(SessionManager)>>onUnhandledError:}
	receiver: a JadeSessionManager
	arg[0]: a DOMParseError

{20EA0624: cf 20EA0609, sp 20EA0638, bp 20EA0624, ip 5, DOMParseError(Error)>>defaultAction}
	receiver: a DOMParseError

{20EA0608: cf 20EA05D5, sp 20EA061C, bp 20EA05F0, ip 55, DOMParseError(Exception)>>_propagateFrom:}
	receiver: a DOMParseError
	arg[0]: a ExceptionHandler
	stack temp[0]: nil
	stack temp[1]: a ExceptionHandler
	stack temp[2]: nil
	stack temp[3]: a Process('Main' base 20EA0000* in SessionManager>>logError: sp=00000000 ip=4 list=028C0010)
	stack temp[4]: nil

{20EA05D4: cf 20EA05B5, sp 20EA05E8, bp 20EA05D0, ip 6, DOMParseError(Exception)>>_propagate}
	receiver: a DOMParseError
	stack temp[0]: nil

{20EA05B4: cf 20EA0599, sp 20EA05C8, bp 20EA05B4, ip 13, DOMParseError(Exception)>>signal}
	receiver: a DOMParseError

{20EA0598: cf 20EA0575, sp 20EA05AC, bp 20EA0590, ip 8, DOMParseError(Exception)>>signal:with:}
	receiver: a DOMParseError
	arg[0]: 'Error parsing XML text'
	arg[1]: a IXMLDOMParseError

{20EA0574: cf 20EA0551, sp 20EA0588, bp 20EA056C, ip 6, DOMParseError class(Exception class)>>signal:with:}
	receiver: DOMParseError
	arg[0]: 'Error parsing XML text'
	arg[1]: a IXMLDOMParseError

{20EA0550: cf 20EA0531, sp 20EA0564, bp 20EA054C, ip 11, IXMLDOMDocument>>loadText:}
	receiver: a IXMLDOMDocument
	arg[0]: '﻿<?xml version="1.0"?>\xd\xa<JadeLogin gemVersion="64-bit 3.6.0 unreleased" stoneH...'

{20EA0530: cf 20EA0509, sp 20EA0544, bp 20EA0528, ip 5, JadeLogin>>initializeFromXML:}
	receiver: a JadeLogin
	arg[0]: '﻿<?xml version="1.0"?>\xd\xa<JadeLogin gemVersion="64-bit 3.6.0 unreleased" stoneH...'
	stack temp[0]: nil

{20EA0508: cf 20EA04E9, sp 20EA0520, bp 20EA0504, ip 7, JadeLogin class>>fromXML:}
	receiver: JadeLogin
	arg[0]: '﻿<?xml version="1.0"?>\xd\xa<JadeLogin gemVersion="64-bit 3.6.0 unreleased" stoneH...'

{20EA04E8: cf 20EA04C1, sp 20EA04FC, bp 20EA04E4, ip 34, JadeLogin class>>default}
	receiver: JadeLogin
	stack temp[0]: L'C:\Users\akogan\AppData\Roaming\JadeDefaultConnection.gss'
	env temp[0]: a FileStream
	env temp[1]: '﻿<?xml version="1.0"?>\xd\xa<JadeLogin gemVersion="64-bit 3.6.0 unreleased" stoneH...'

{20EA04C0: cf 20EA04A1, sp 20EA04DC, bp 20EA04C0, ip 71, JadeLoginShell>>loadData}
	receiver: a JadeLoginShell
	env temp[0]: a OrderedCollection

{20EA04A0: cf 20EA0481, sp 20EA04B8, bp 20EA04A0, ip 17, JadeLoginShell>>onViewOpened}
	receiver: a JadeLoginShell

{20EA0480: cf 20EA0461, sp 20EA0498, bp 20EA047C, ip 7, JadeLoginShell(Shell)>>view:}
	receiver: a JadeLoginShell
	arg[0]: a ShellView

{20EA0460: cf 20EA043D, sp 20EA0474, bp 20EA0458, ip 17, JadeLoginShell(Shell)>>createView:}
	receiver: a JadeLoginShell
	arg[0]: 'Default view'
	stack temp[0]: a DesktopView

{20EA043C: cf 20EA0419, sp 20EA0450, bp 20EA0434, ip 6, JadeLoginShell class(Shell class)>>create:}
	receiver: JadeLoginShell
	arg[0]: 'Default view'
	stack temp[0]: a JadeLoginShell

{20EA0418: cf 20EA03FD, sp 20EA042C, bp 20EA0418, ip 4, JadeLoginShell class(Presenter class)>>create}
	receiver: JadeLoginShell

{20EA03FC: cf 20EA03E1, sp 20EA0410, bp 20EA03FC, ip 2, JadeLoginShell class(Presenter class)>>show}
	receiver: JadeLoginShell

{20EA03E0: cf 20EA03C5, sp 20EA03F4, bp 20EA03E0, ip 17, JadeSessionManager>>main}
	receiver: a JadeSessionManager

{20EA03C4: cf 20EA03A9, sp 20EA03D8, bp 20EA03C4, ip 5, JadeSessionManager(SessionManager)>>mainLoopStarted}
	receiver: a JadeSessionManager

{20EA03A8: cf 20EA038D, sp 20EA03BC, bp 20EA03A8, ip 10, [] in JadeSessionManager(SessionManager)>>forkMain}
	receiver: a JadeSessionManager

{20EA038C: cf 20EA0361, sp 20EA03A0, bp 20EA037C, ip 43, GuiInputState(InputState)>>loopWhile:}
	receiver: a GuiInputState
	arg[0]: [] @ 9 in InputState>>mainLoop
	stack temp[0]: a MSG
	stack temp[1]: true
	stack temp[2]: [] @ 9 in SessionManager>>forkMain

{20EA0360: cf 20EA0345, sp 20EA0374, bp 20EA0360, ip 15, GuiInputState(InputState)>>mainLoop}
	receiver: a GuiInputState

{20EA0344: cf 20EA0329, sp 20EA0358, bp 20EA0344, ip 14, [] in GuiInputState(InputState)>>forkMain}
	receiver: a GuiInputState

{20EA0328: cf 20EA030D, sp 20EA033C, bp 20EA0328, ip 13, ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry}
	receiver: a ExceptionHandler

{20EA030C: cf 20EA02E5, sp 20EA0320, bp 20EA0308, ip 22, [] in ExceptionHandler(ExceptionHandlerAbstract)>>try:}
	receiver: a ExceptionHandler

{20EA02E4: cf 20EA02C5, sp 20EA02F8, bp 20EA02E0, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 39 in ExceptionHandlerAbstract>>try:

{20EA02C4: cf 20EA02A1, sp 20EA02D8, bp 20EA02BC, ip 3, BlockClosure>>ensure:}
	receiver: [] @ 17 in ExceptionHandlerAbstract>>try:
	arg[0]: [] @ 39 in ExceptionHandlerAbstract>>try:
	stack temp[0]: nil

{20EA02A0: cf 20EA0279, sp 20EA02B4, bp 20EA0294, ip 44, ExceptionHandler(ExceptionHandlerAbstract)>>try:}
	receiver: a ExceptionHandler
	arg[0]: [] @ 10 in InputState>>forkMain
	stack temp[0]: nil
	stack temp[1]: a Process('Main' base 20EA0000* in SessionManager>>logError: sp=00000000 ip=4 list=028C0010)
	env temp[0]: nil

{20EA0278: cf 20EA0255, sp 20EA028C, bp 20EA0270, ip 7, BlockClosure>>on:do:}
	receiver: [] @ 10 in InputState>>forkMain
	arg[0]: ProcessTermination
	arg[1]: [] @ 13 in BlockClosure>>newProcess:

{20EA0254: cf 00000001, sp 20EA0268, bp 20EA0254, ip 17, [] in BlockClosure>>newProcess:}
	receiver: [] @ 10 in InputState>>forkMain

<Bottom of stack>

***** End of dump *****

************************** Dolphin Virtual Machine Dump Report ***************************

16:29:20 PM, 7/10/2020: Error parsing XML text - 'Invalid at the top level of the document.' at 1, 1

*----> VM Context <----*
Process: {20EA0210:size 239 words, suspended frame 20EA24C5, priority 5, callbacks 0, FP control 80007, thread 00000000}
Active Method: SessionManager>>logError:
IP: 1AB95F19 (9)
SP: 20EA06AC
BP: 20EA0680 (269)
ActiveFrame: {20EA0684: cf 20EA0665, sp 20EA069C, bp 20EA0680, ip 5, JadeSessionManager(SessionManager)>>logError:}
	receiver: a JadeSessionManager
	arg[0]: a DOMParseError

New Method: VMLibrary>>dump:path:stackDepth:walkbackDepth:
Message Selector: dump:path:stackDepth:walkbackDepth:

*----> Stack Back Trace <----*
{20EA0684: cf 20EA0665, sp 20EA069C, bp 20EA0680, ip 5, JadeSessionManager(SessionManager)>>logError:}
	receiver: a JadeSessionManager
	arg[0]: a DOMParseError

{20EA0664: cf 20EA0645, sp 20EA0678, bp 20EA0660, ip 3, JadeSessionManager(SessionManager)>>unhandledException:}
	receiver: a JadeSessionManager
	arg[0]: a DOMParseError

{20EA0644: cf 20EA0625, sp 20EA0658, bp 20EA0640, ip 3, JadeSessionManager(SessionManager)>>onUnhandledError:}
	receiver: a JadeSessionManager
	arg[0]: a DOMParseError

{20EA0624: cf 20EA0609, sp 20EA0638, bp 20EA0624, ip 5, DOMParseError(Error)>>defaultAction}
	receiver: a DOMParseError

{20EA0608: cf 20EA05D5, sp 20EA061C, bp 20EA05F0, ip 55, DOMParseError(Exception)>>_propagateFrom:}
	receiver: a DOMParseError
	arg[0]: a ExceptionHandler
	stack temp[0]: nil
	stack temp[1]: a ExceptionHandler
	stack temp[2]: nil
	stack temp[3]: a Process('Main' base 20EA0000* in SessionManager>>logError: sp=00000000 ip=4 list=02920010)
	stack temp[4]: nil

{20EA05D4: cf 20EA05B5, sp 20EA05E8, bp 20EA05D0, ip 6, DOMParseError(Exception)>>_propagate}
	receiver: a DOMParseError
	stack temp[0]: nil

{20EA05B4: cf 20EA0599, sp 20EA05C8, bp 20EA05B4, ip 13, DOMParseError(Exception)>>signal}
	receiver: a DOMParseError

{20EA0598: cf 20EA0575, sp 20EA05AC, bp 20EA0590, ip 8, DOMParseError(Exception)>>signal:with:}
	receiver: a DOMParseError
	arg[0]: 'Error parsing XML text'
	arg[1]: a IXMLDOMParseError

{20EA0574: cf 20EA0551, sp 20EA0588, bp 20EA056C, ip 6, DOMParseError class(Exception class)>>signal:with:}
	receiver: DOMParseError
	arg[0]: 'Error parsing XML text'
	arg[1]: a IXMLDOMParseError

{20EA0550: cf 20EA0531, sp 20EA0564, bp 20EA054C, ip 11, IXMLDOMDocument>>loadText:}
	receiver: a IXMLDOMDocument
	arg[0]: '﻿<?xml version="1.0"?>\xd\xa<JadeLogin gemVersion="64-bit 3.6.0 unreleased" stoneH...'

{20EA0530: cf 20EA0509, sp 20EA0544, bp 20EA0528, ip 5, JadeLogin>>initializeFromXML:}
	receiver: a JadeLogin
	arg[0]: '﻿<?xml version="1.0"?>\xd\xa<JadeLogin gemVersion="64-bit 3.6.0 unreleased" stoneH...'
	stack temp[0]: nil

{20EA0508: cf 20EA04E9, sp 20EA0520, bp 20EA0504, ip 7, JadeLogin class>>fromXML:}
	receiver: JadeLogin
	arg[0]: '﻿<?xml version="1.0"?>\xd\xa<JadeLogin gemVersion="64-bit 3.6.0 unreleased" stoneH...'

{20EA04E8: cf 20EA04C1, sp 20EA04FC, bp 20EA04E4, ip 34, JadeLogin class>>default}
	receiver: JadeLogin
	stack temp[0]: L'C:\Users\akogan\AppData\Roaming\JadeDefaultConnection.gss'
	env temp[0]: a FileStream
	env temp[1]: '﻿<?xml version="1.0"?>\xd\xa<JadeLogin gemVersion="64-bit 3.6.0 unreleased" stoneH...'

{20EA04C0: cf 20EA04A1, sp 20EA04DC, bp 20EA04C0, ip 71, JadeLoginShell>>loadData}
	receiver: a JadeLoginShell
	env temp[0]: a OrderedCollection

{20EA04A0: cf 20EA0481, sp 20EA04B8, bp 20EA04A0, ip 17, JadeLoginShell>>onViewOpened}
	receiver: a JadeLoginShell

{20EA0480: cf 20EA0461, sp 20EA0498, bp 20EA047C, ip 7, JadeLoginShell(Shell)>>view:}
	receiver: a JadeLoginShell
	arg[0]: a ShellView

{20EA0460: cf 20EA043D, sp 20EA0474, bp 20EA0458, ip 17, JadeLoginShell(Shell)>>createView:}
	receiver: a JadeLoginShell
	arg[0]: 'Default view'
	stack temp[0]: a DesktopView

{20EA043C: cf 20EA0419, sp 20EA0450, bp 20EA0434, ip 6, JadeLoginShell class(Shell class)>>create:}
	receiver: JadeLoginShell
	arg[0]: 'Default view'
	stack temp[0]: a JadeLoginShell

{20EA0418: cf 20EA03FD, sp 20EA042C, bp 20EA0418, ip 4, JadeLoginShell class(Presenter class)>>create}
	receiver: JadeLoginShell

{20EA03FC: cf 20EA03E1, sp 20EA0410, bp 20EA03FC, ip 2, JadeLoginShell class(Presenter class)>>show}
	receiver: JadeLoginShell

{20EA03E0: cf 20EA03C5, sp 20EA03F4, bp 20EA03E0, ip 17, JadeSessionManager>>main}
	receiver: a JadeSessionManager

{20EA03C4: cf 20EA03A9, sp 20EA03D8, bp 20EA03C4, ip 5, JadeSessionManager(SessionManager)>>mainLoopStarted}
	receiver: a JadeSessionManager

{20EA03A8: cf 20EA038D, sp 20EA03BC, bp 20EA03A8, ip 10, [] in JadeSessionManager(SessionManager)>>forkMain}
	receiver: a JadeSessionManager

{20EA038C: cf 20EA0361, sp 20EA03A0, bp 20EA037C, ip 43, GuiInputState(InputState)>>loopWhile:}
	receiver: a GuiInputState
	arg[0]: [] @ 9 in InputState>>mainLoop
	stack temp[0]: a MSG
	stack temp[1]: true
	stack temp[2]: [] @ 9 in SessionManager>>forkMain

{20EA0360: cf 20EA0345, sp 20EA0374, bp 20EA0360, ip 15, GuiInputState(InputState)>>mainLoop}
	receiver: a GuiInputState

{20EA0344: cf 20EA0329, sp 20EA0358, bp 20EA0344, ip 14, [] in GuiInputState(InputState)>>forkMain}
	receiver: a GuiInputState

{20EA0328: cf 20EA030D, sp 20EA033C, bp 20EA0328, ip 13, ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry}
	receiver: a ExceptionHandler

{20EA030C: cf 20EA02E5, sp 20EA0320, bp 20EA0308, ip 22, [] in ExceptionHandler(ExceptionHandlerAbstract)>>try:}
	receiver: a ExceptionHandler

{20EA02E4: cf 20EA02C5, sp 20EA02F8, bp 20EA02E0, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 39 in ExceptionHandlerAbstract>>try:

{20EA02C4: cf 20EA02A1, sp 20EA02D8, bp 20EA02BC, ip 3, BlockClosure>>ensure:}
	receiver: [] @ 17 in ExceptionHandlerAbstract>>try:
	arg[0]: [] @ 39 in ExceptionHandlerAbstract>>try:
	stack temp[0]: nil

{20EA02A0: cf 20EA0279, sp 20EA02B4, bp 20EA0294, ip 44, ExceptionHandler(ExceptionHandlerAbstract)>>try:}
	receiver: a ExceptionHandler
	arg[0]: [] @ 10 in InputState>>forkMain
	stack temp[0]: nil
	stack temp[1]: a Process('Main' base 20EA0000* in SessionManager>>logError: sp=00000000 ip=4 list=02920010)
	env temp[0]: nil

{20EA0278: cf 20EA0255, sp 20EA028C, bp 20EA0270, ip 7, BlockClosure>>on:do:}
	receiver: [] @ 10 in InputState>>forkMain
	arg[0]: ProcessTermination
	arg[1]: [] @ 13 in BlockClosure>>newProcess:

{20EA0254: cf 00000001, sp 20EA0268, bp 20EA0254, ip 17, [] in BlockClosure>>newProcess:}
	receiver: [] @ 10 in InputState>>forkMain

<Bottom of stack>

***** End of dump *****

**Comment by jgfoster** [comment]
Believed to be fixed by c86de32ea2cf22d8b81684cd825fd6e7dd25ee20.
