### ISSUE TITLE
Missing Preferences: "Show unimplemented messages"

### ISSUE THREAD

**Issue by PeterMoe** [jgfoster/Jade.bak#268]
Hi James,

in the newer version in the preferences I don't find the option to disable the "show unimplemented messages" see last comment at #117 
can you please reimplement it plus add the "save" option? 😃 

Regards
Peter

**Comment by jgfoster** [comment]
@brunobuzzi, Do you have any insight into the preference for "show unimplemented messages"?

@PeterMoe, Is the "save" option something needed in preferences or in the method editor?

**Comment by brunobuzzi** [comment]
@jgfoster i will take a look. Preferences can be easily added. I will create a PR give me a couple of days to find some time 😁

**Comment by PeterMoe** [comment]
@jgfoster , every time when i relog to DB i have to activate the option. Will be nice to save the last taken decision(save it).

**Comment by jgfoster** [comment]
I believe that this is the same problem as #269 in that the preferences were not being included in the runtime build.
