### ISSUE TITLE
Method List Browser: Switch to Tree View / Switch to List View

### ISSUE THREAD

**Issue by PeterMoe** [jgfoster/Jade.bak#269]
Hi James and Bruno,

in version 2.4.6 in the "Method List Browser" in the menu i can't find the entry "Switch to Tree View / Switch to List View" in some cases it was a nice option. This option was available in v. 2.3.11.

Regards
Peter

**Comment by brunobuzzi** [comment]
Try the following:
![imagen](https://user-images.githubusercontent.com/4719282/94564044-e13c0600-023d-11eb-9d69-ff16eb7307f5.png)

**Comment by PeterMoe** [comment]
Hi Bruno,

i have an other Jade Version, and not correct icons ? 

![JadePreferences_2020-10-01](https://user-images.githubusercontent.com/40350726/94775466-25efaa80-03c0-11eb-83ea-95e358316e80.jpg)

Using Jade 2.4.6 on Windows 10:
![JadeVersion_2020-10-01](https://user-images.githubusercontent.com/40350726/94775565-5cc5c080-03c0-11eb-8e72-ef6cf1e0f84a.jpg)

**Comment by PeterMoe** [comment]
@brunobuzzi do you have some update for me. have i a faulty Jade version or some other Problems?

**Comment by PeterMoe** [comment]
@brunobuzzi or @jgfoster I don't have the same number of options as brunobuzzi, some Idea?

**Comment by brunobuzzi** [comment]
Indeed there is a problem with .EXE because in my Jade Programming environment i have all options and in my .EXE some options are missing. I will research on this:
![imagen](https://user-images.githubusercontent.com/4719282/98573105-33d4fd00-2295-11eb-817a-c7461f94f411.png)

**Comment by jgfoster** [comment]
The image stripping removes classes that it doesn't recognize as being used. Therefore, code like `JadePreferencesShell class>>defaultModel` need to do more than simply `JadePreferenceObject allSubclasses`. Similar code needs to be added to `JadeImageStripper>>requiredClasses' so that they aren't stripped.
