### ISSUE TITLE
Inspect/Display of DateAndTime now answers nil in GS 3.6.0

### ISSUE THREAD

**Issue by ramauers** [jgfoster/Jade.bak#272]
Hi guys,
I observed the following:

DateAndTime now asString -->  '2020-12-09T04:55:10,079137-08:00'
DateAndTime now class  --> SmallDateAndTime
DateAndTime now isNil --> false

BUT:

DateAndTime now  --> nil

Br,
Ralph

**Comment by jgfoster** [comment]
Good catch! SmallDateAndTime is an immediate that Jade doesn't recognize. We should be able to fix that soon. Until then you have the #'asString' work-around...

**Comment by feldti** [comment]
Any idea on this ?

**Comment by jgfoster** [comment]
I need to figure out the internal format of these new immediate values and convert them from an OOP to a Dolphin object on the client. I'm sorry I haven't gotten to it.

**Comment by feldti** [comment]
Hey, the 2.4.9 (just tested against a 3.6 database) did not fix this. I get empty inspector windows with this version for "Date today", "Time now" and "DateAndTime now".

**Comment by feldti** [comment]
I tried to reopen this issue, but it seems, that only the owner is allowed to do this ?. Other than that: thanks for your continous work on this tool ... without it Gemstone/S programming would not be that nice.

**Comment by jgfoster** [comment]
Interesting. I'll reopen this but I'm not sure how I can debug it since it works for me. Could you prepare a screen shot that looks like the following?

![Screen Shot 2021-02-19 at 7 44 13 AM](https://user-images.githubusercontent.com/1577872/108526701-4c868300-7286-11eb-970e-bf331f0ffa16.png)

**Comment by ramauers** [comment]
I can reproduce a screenshot like James provided, so printing (using CTRL-D) works. But opening an inspector (CTRL-Q) just opens an empty window showing UndefinedObject / nil.

**Comment by feldti** [comment]
![jade_2_4_9](https://user-images.githubusercontent.com/24528907/108812805-0bf17700-75b0-11eb-8c73-6d2df2d6278b.png)

The empty windows shows the inspect of the DateAndTime now

**Comment by feldti** [comment]
NLS issue somehow ? $. aginst $, ?
