### ISSUE TITLE
Method list browser missing senders/implementers

### ISSUE THREAD

**Issue by jgfoster** [jgfoster/Jade.bak#31]
This should use the same widget as the system browser so that the features are the same. 
Ideally the same widget would be used in the debugger as well.

**Comment by jgfoster** [comment]
I have something in https://github.com/jgfoster/Jade/raw/methodSourcePresenter/runtime/Jade.exe that I believe addresses this.

**Comment by feldti** [comment]
Well, I meant something different: When I view a method in the main browser view I want to look for an implementor of a method used in that method. Now a Method List Browser opens and I select a method and the same start again and again ... read the method, show me an implementor of the method used there and again and again ...

**Comment by feldti** [comment]
You could simulate that by coping the name of a selector found within that method and then select "Browse Method containing ..." - but thats pretty boring ...

**Comment by feldti** [comment]
Yes, that did it !

**Comment by jgfoster** [comment]
Merged fix in b6fa32da99e30acef14bf4c5f4a0271279c09581.
