### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by jgfoster** [jgfoster/Jade.bak#36]
Needs work

**Comment by brunobuzzi** [comment]
Hi, 
I can take this issue but without finish date :)
The goal it will be Jade Autocompletion to be equal to Dolphin Autocompletion.
Also i will send pull request (now i'm more familiar with git) to add SUnit (may be this is other issue).

**Comment by brunobuzzi** [comment]
Currently working on this... 
Reimplementing the autocompletion workspace. Now it use Scintilla functions to get text from the code pane (instead of my quick & dirty string manipulation).
