### ISSUE TITLE
Detailed Textual  Explanation of Errors while compiling

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade.bak#46]
Working under Linux/Wine I noticed that - when a compiling error occurs - I can not see, where the error is. It would be nice to get a more detailed error message than "UndefinedSymbol" on the bottom of the code browser. At least the name would be nice and a possible line number would also be good (though line numbers are not shown in the code browser - but that may be changed later)

**Comment by jgfoster** [comment]
There used to be a red squiggle identifying the location of a compile error. It was lost and has been restored. Thanks for the report!
