### ISSUE TITLE
Following an implementor flow is difficult

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade.bak#49]
When I have a method and I want to see an implementor of a method used in that method I get a method list browser - but from there on nothing can be done - no further navigation, not changing the source code etc ...

**Comment by jgfoster** [comment]
Same as issue #31 (but thanks for the report; the reminder has moved it up on the priority list!).

**Comment by jgfoster** [comment]
Would you be willing to try the executable at https://github.com/jgfoster/Jade/raw/methodSourcePresenter/runtime/Jade.exe and add comments to #31? Thanks!
