### ISSUE TITLE
GciSession error on 3.2.3 while upgrading GsDevKit

### ISSUE THREAD

**Issue by HeSe** [jgfoster/Jade.bak#5]
I get a GciSesison does not understand #signalInformRequestUsing: error while perfomring this on a viring gsDevKitHome stone based on 3.2.3. 

Gofer new
  package: 'GsUpgrader-Core';
  repository: (MCGitHubRepository location: 'github://GsDevKit/gsUpgrader:dev/repository');
  load.
(Smalltalk at: #GsUpgrader) upgradeGsDevKit.

**Comment by jgfoster** [comment]
Thanks for the report. I've added support for OBInformRequest so that it puts up a notify MessageBox.
