### ISSUE TITLE
System Browser - Tab "Globals"

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade.bak#52]
The tabs does nothing - should it be removed ?

**Comment by jgfoster** [comment]
Actually, the first list has choices between Packages and Dictionaries. If you select Dictionaries then the Globals will show the contents of the selected dictionary. To avoid this confusion we could hide the tab if you select Packages, or we could fill it with a message explaining that Packages don't have globals (or at least we don't show them).

**Comment by jgfoster** [comment]
Merged 034135966b5439561dba0906a7904597073ee2fe.
