### ISSUE TITLE
System Browser - Tab "Original Source"

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade.bak#53]
The tab does nothing - should it be removed ?

**Comment by jgfoster** [comment]
There are some methods that have replacements (called Session Methods) provided by a package. Take a look at Behavior>>#'classVarNames' or Behavior>>#'compileMethod:dictionaries:category:environmentId:' for examples of the base method and the Session Method. To the extent that this is confusing, we could either hide the tab or fill it with something description. Suggestions?

**Comment by jgfoster** [comment]
Merged 034135966b5439561dba0906a7904597073ee2fe.
