### ISSUE TITLE
2.0.15 - no Monticello package saving possible any more ...

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade.bak#54]
With this version I'm not able to save/store a package into a server directory any more. ("Save Package"). Get an error "UndefinedObject does not understand #appendToStream:"

**Comment by jgfoster** [comment]
Still trying to figure out what changed, because the specific error causing the walkback has been there a long time yet clearly things worked until recently. Anyway, thanks for the report and I think it is fixed now.
