### ISSUE TITLE
Older versions of binary should be also offered for download

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade.bak#56]
I would be nice to have older binaries also available for download - otherwise we have periods of time, where only "strange" versions are available.

**Comment by jgfoster** [comment]
Open a browser to https://github.com/jgfoster/Jade/commits/master/runtime/Jade.exe or https://github.com/jgfoster/Jade/commits/master/runtime/Jade.zip, find the desired build/tag, click the "Browse the repository at this point in the history" button on the right [<>], then click the [Download] button.
