### ISSUE TITLE
filetree repository not seeing packages

### ISSUE THREAD

**Issue by sebastianconcept** [jgfoster/Jade.bak#57]
Hi @jgfoster I'm enjoying Jade and thanks for making the `macOS` app!

I'm on `2.0.13` which I've downloaded from:
http://seaside.gemtalksystems.com/jade/

With monticello packages the save/load is fine but when trying to add a filetree repo, it doesn't see the packages that are there.

**Comment by jgfoster** [comment]
I've created a FileTree repository, saved a package, then deleted references to the repository from GemStone using the Monticello Browser UI. When I then create another FileTree repository using the same server directory, it properly shows the one package I previously saved to that location. If this can be reproduced with more detailed steps, then it should be reopened.
