### ISSUE TITLE
Methods Tracking (recently visited methods) is not installed by default

### ISSUE THREAD

**Issue by brunobuzzi** [jgfoster/Jade.bak#61]
We must update BootJade.st. 
But first a refactoring of some packages are needed. Some classes and methods need to be moved from one package to another. For example:
There is no need for: Jade Autocompletation and Jade Autocompletation Enhancements. All should be moved to one package.
After this refactoring --> update BootJade.st (if necessary)

**Comment by brunobuzzi** [comment]
After a initial analysis it seems that BootJade.st should use:
SmalltalkSystem>>installPackage: instead of PackageManager current install: .

Because SmalltalkSystem>>installPackage: will let you to install clashing elements.
I will check this and create a pull request.

**Comment by jgfoster** [comment]
The current master doesn't display any clashing elements. While I find clashes annoying, I've been able to refactor things (by moving classes, methods, or the load order) to get things to work. What problems/conflicts/clashes are you observing?

**Comment by brunobuzzi** [comment]
In the current version by default the following packages are NOT loaded:
Jade from Dolphin
Jade Autocompletation Enhancements.pax
Jade Test Browser
Jade System Browser Tracking.

If add them to BootJade.st and try to boot all again --> a clash stop the booting process.

**Comment by jgfoster** [comment]
I think that 'Jade from Dolphin' is no longer needed (it dates from the time that we got special permission to use some "non-distributable" classes and with Dolphin open source that limitation no longer exists). I should probably delete it from Git.

As to the others, I'm open to your ideas. My primary concern with something that will let you install clashing elements is that the clashes are ultimately resolved.

**Comment by brunobuzzi** [comment]
Yes. Jade from Dolphin is no longer needed. 
I have to move classes from packages in order to get rid of the clashes. 
If can solve this locally (i think yes) i will send the pull request.
One idea is to move all Autocompletation to Jade UI Base.
There are lof of to check before doing it.

**Comment by brunobuzzi** [comment]
James, I got all package loaded (no clashes) changing  BootJade.st (let check everything before sending the PR):
2 changes:
1) 
Add 	'Jade Autocompletation Enhancements' 'Jade Test Browser' 'Jade System Browser Tracking' at the end of the package to install list.
2)
"PackageManager current install: 'sources\' , name , '.pax'."
[PackageManager current install: ('sources\' , name , '.pax')] on: Package clashSignal do: [:ex | ex resume].

The second step avoid the Clashes.

**Comment by jgfoster** [comment]
My recent changes do not include this issue. I'll reopen it and we'll figure out how to incorporate it.

**Comment by brunobuzzi** [comment]
James, i got everything in STS in Dolphin. I can do it !

**Comment by jgfoster** [comment]
I think this is fixed; #39 is still open with other issues.
