### ISSUE TITLE
Need to remove references to PackageOrganizer from JadeServer

### ISSUE THREAD

**Issue by jgfoster** [jgfoster/Jade.bak#73]
PackageOrganizer does not exist in a base extent ($GEMSTONE/bin/extent0.dbf) so should not be directly referenced in any required Jade code. Any features that rely on PackageOrganizer should be enabled or disabled based on its presence (as is done now with the package list vs. dictionary list).

**Comment by brunobuzzi** [comment]
If PackageOrganizer class does not exist in some GS versions --> Jade Test Browser package is the problem.
I will check this dependency !

**Comment by brunobuzzi** [comment]
When log in as SystemUser then (GS64 3.3.3):
* SUnitBrowser does not open and popup a GS Walkback.
* SUnitTab in SystemBrowser does not show any error but is not functional.

**Comment by brunobuzzi** [comment]
Also "allButLast" method does not exist in all GS environments.

**Comment by jgfoster** [comment]
Have you tested a runtime build (see #74)?

**Comment by brunobuzzi** [comment]
Runtime is failing due to SciLexer !, checking now !

**Comment by brunobuzzi** [comment]
I have copied SciLexer to runtime directory and it seems to works (same directory as the exe).
The other error is because Jade.exe is an old .exe and is still using method that directly reference PackageOrganizer. 
![imagen](https://cloud.githubusercontent.com/assets/4719282/23676137/77a77ab6-035a-11e7-9e23-8ca3ceeb896b.png)

**Comment by brunobuzzi** [comment]
There is also:
JadeImageStripper>>requiredPackageNames
Not sure if you have to update this methods with new packages like 'BootJade.st'.

**Comment by jgfoster** [comment]
Yes, the SciLexer.dll needs to be updated periodically and copying it from Dolphin to Jade/bin and Jade/runtime/bin is usually sufficient.

As to the runtime, have you ever built a runtime? If not, to do so select the 'Jade Deployment' package, then select the 'Deployment' menu command from the context (right-click) menu, and the 'Deploy Executable...' command. From the wizard, select Deploy (bottom right) or step through the wizard tabs.

**Comment by brunobuzzi** [comment]
Yes, i tried but Dolphin is giving an error on: JadeSessionManager getVersion.
SessionManager current class git: 'describe'. " this is NOT working in my image"

**Comment by jgfoster** [comment]
Well, that is something that we should fix! 

What error do you get? Do you have a method DevelopmentSessionManager class>>#'git:' in your Dolphin image? For me it is part of the 'Development System' package. 

If so, does 'ExternalPipe example1' work (evaluate it in a workspace)? In the example, try 'git --version' to see if git is visible from Dolphin. If not, then we need to decide if it should be required to build Jade...

**Comment by jgfoster** [comment]
As a work-around you might modify JadeSessionManager class>>#'getVersion' with an Exception handler that simply returns something that is clearly not a git version, such as '???'.

**Comment by brunobuzzi** [comment]
i have to test this at home there are lot of firewall here. Let you know the results...

**Comment by jgfoster** [comment]
Fixed with f5061a7fba4aa9413631bf0037e257d947719be5.
