### ISSUE TITLE
Create a User Preferences Window

### ISSUE THREAD

**Issue by brunobuzzi** [jgfoster/Jade.bak#95]
Tree Method Browser is activated using a MenuBar in the Method Browser (and viceversa) which is not a standart behavior. 
Check all other options to be put in the same window.
Make a User Preferences to include all possible user's options for Jade Development Environment.

**Comment by jgfoster** [comment]
Basic implementation provided with 1a7fc0bf9df0b750406cd330e443c3676a71d50c.
