### ISSUE TITLE
Secondary highlights of selected text

### ISSUE THREAD

**Issue by jgfoster** [jgfoster/Jade.bak#97]
It would be nice to have a secondary highlight of text that matches selected text. That is, if you double click on a method argument or a temporary variable name, it shows you all the references to that variable. This is not directly supported in Scintilla, but is done in other applications that use Scintilla. See, for example, highlight.current.word in http://www.scintilla.org/SciTEDoc.html.

**Comment by brunobuzzi** [comment]
I have this feature working:
![image](https://user-images.githubusercontent.com/4719282/35528534-e448b7a2-050c-11e8-9485-77fc09f638d9.png)

**Comment by brunobuzzi** [comment]
Scintilla.secondarySelectionBackcolor is harcoded for now (it should be configurable).
...
view secondarySelectionBackcolor: RGB yellow. "this should be configurable in future implementations"
....

**Comment by brunobuzzi** [comment]
The multiple paste problem is still in JadeDebugger. 
Until now i was not able to trap Ctrl + C (with keyboards) in JadeDebugger.
i checked the command routing (view commandPolicy) and tried to trap it in these presenters but no luck.

**Comment by jgfoster** [comment]
We have secondary highlight with fixed format. Issue #138 discusses making it configurable. Other issues discussed here ("The multiple paste problem") should be raised in separate issues if they still exist.
